// ============================================================
// WOSHICND — Données : radicaux clés + vocabulaire décomposé
// ============================================================

// Radicaux "fondations" : les briques qui reviennent partout.
// Servent de base ET de filtre croisé (clique un radical → tous les mots qui le contiennent)
const RADICALS = {
  '木': { pinyin: 'mù', meaning: 'bois / arbre', family: 'nature' },
  '艹': { pinyin: 'cǎo', meaning: 'plante / herbe', family: 'nature' },
  '氵': { pinyin: 'shuǐ', meaning: 'eau', family: 'nature' },
  '火': { pinyin: 'huǒ', meaning: 'feu', family: 'nature' },
  '灬': { pinyin: 'huǒ', meaning: 'feu (variante basse)', family: 'nature' },
  '土': { pinyin: 'tǔ', meaning: 'terre', family: 'nature' },
  '金': { pinyin: 'jīn', meaning: 'métal / or', family: 'nature' },
  '鸟': { pinyin: 'niǎo', meaning: 'oiseau', family: 'animal' },
  '隹': { pinyin: 'zhuī', meaning: 'oiseau (forme ancienne)', family: 'animal' },
  '犭': { pinyin: 'quǎn', meaning: 'animal à 4 pattes (chien)', family: 'animal' },
  '鱼': { pinyin: 'yú', meaning: 'poisson', family: 'animal' },
  '虫': { pinyin: 'chóng', meaning: 'insecte / bestiole', family: 'animal' },
  '豕': { pinyin: 'shǐ', meaning: 'cochon', family: 'animal' },
  '饣': { pinyin: 'shí', meaning: 'nourriture', family: 'nourriture' },
  '米': { pinyin: 'mǐ', meaning: 'riz / grain', family: 'nourriture' },
  '口': { pinyin: 'kǒu', meaning: 'bouche', family: 'corps' },
  '女': { pinyin: 'nǚ', meaning: 'femme', family: 'autre' },
  '子': { pinyin: 'zǐ', meaning: 'enfant', family: 'autre' },
  '人': { pinyin: 'rén', meaning: 'personne', family: 'autre' },
  '日': { pinyin: 'rì', meaning: 'soleil / jour', family: 'nature' },
  '月': { pinyin: 'yuè', meaning: 'lune / mois / chair', family: 'nature' },
  '山': { pinyin: 'shān', meaning: 'montagne', family: 'nature' },
};

// Catégories affichées dans le menu, dans l'ordre
const CATEGORIES = [
  { id: 'fondations', label: 'Fondations', sub: 'LES BRIQUES DE BASE' },
  { id: 'animaux', label: 'Animaux', sub: '动物 · DŌNGWÙ' },
  { id: 'fruits', label: 'Fruits', sub: '水果 · SHUǏGUǑ' },
  { id: 'legumes', label: 'Légumes', sub: '蔬菜 · SHŪCÀI' },
  { id: 'nourriture', label: 'Nourriture', sub: '食物 · SHÍWÙ' },
  { id: 'phrases', label: 'Phrases', sub: '日常用语 · PAR DOMAINE' },
  { id: 'grammaire', label: 'Grammaire', sub: 'PIÈGES & CONNECTEURS' },
  { id: 'ecriture', label: 'Écriture', sub: '写字 · TRACÉ AU DOIGT' },
  { id: 'radicaux', label: 'Radicaux', sub: 'VUE CROISÉE' },
  { id: 'revision', label: 'Révision', sub: 'FLASHCARDS' },
];

// tag: 'sens' (radical de sens), 'son' (composant phonétique), 'mot' (caractère = mot complet dans un mot composé), 'forme' (pictogramme)
const VOCAB = [
  // ---------------- FONDATIONS ----------------
  { id: 'f-mu', hanzi: '木', pinyin: 'mù', fr: 'bois / arbre', cat: 'fondations',
    parts: [{ char: '木', pinyin: 'mù', meaning: 'pictogramme d\'un arbre (tronc + branches + racines)', tag: 'forme' }],
    logic: 'Pictogramme direct : un arbre stylisé.' },
  { id: 'f-cao', hanzi: '艹', pinyin: 'cǎo', fr: 'herbe / plante (radical)', cat: 'fondations',
    parts: [{ char: '艹', pinyin: 'cǎo', meaning: 'deux brins d\'herbe qui poussent', tag: 'forme' }],
    logic: 'Toujours en haut d\'un caractère → indique un lien avec les plantes.' },
  { id: 'f-shui', hanzi: '水', pinyin: 'shuǐ', fr: 'eau', cat: 'fondations',
    parts: [{ char: '水', pinyin: 'shuǐ', meaning: 'pictogramme d\'un courant d\'eau', tag: 'forme' }],
    logic: 'Devient 氵 (3 gouttes) quand il est sur le côté gauche d\'un caractère.' },
  { id: 'f-huo', hanzi: '火', pinyin: 'huǒ', fr: 'feu', cat: 'fondations',
    parts: [{ char: '火', pinyin: 'huǒ', meaning: 'pictogramme de flammes', tag: 'forme' }],
    logic: 'Devient 灬 (4 points) quand il est en bas d\'un caractère.' },
  { id: 'f-tu', hanzi: '土', pinyin: 'tǔ', fr: 'terre', cat: 'fondations',
    parts: [{ char: '土', pinyin: 'tǔ', meaning: 'un tas de terre posé au sol', tag: 'forme' }],
    logic: 'Pictogramme d\'un monticule de terre.' },
  { id: 'f-jin', hanzi: '金', pinyin: 'jīn', fr: 'métal / or', cat: 'fondations',
    parts: [{ char: '金', pinyin: 'jīn', meaning: 'pépites de métal dans la terre', tag: 'forme' }],
    logic: 'Devient 钅 sur le côté gauche d\'un caractère (objets en métal).' },
  { id: 'f-niao', hanzi: '鸟', pinyin: 'niǎo', fr: 'oiseau', cat: 'fondations',
    parts: [{ char: '鸟', pinyin: 'niǎo', meaning: 'pictogramme d\'un oiseau (tête, aile, queue)', tag: 'forme' }],
    logic: 'Radical présent dans quasi tous les noms d\'oiseaux.' },
  { id: 'f-quan', hanzi: '犭', pinyin: 'quǎn', fr: 'animal à 4 pattes (radical)', cat: 'fondations',
    parts: [{ char: '犭', pinyin: 'quǎn', meaning: 'forme raccourcie de 犬 (chien)', tag: 'forme' }],
    logic: 'Toujours à gauche → signale un mammifère à 4 pattes.' },
  { id: 'f-yu', hanzi: '鱼', pinyin: 'yú', fr: 'poisson', cat: 'fondations',
    parts: [{ char: '鱼', pinyin: 'yú', meaning: 'pictogramme d\'un poisson (tête, écailles, queue)', tag: 'forme' }],
    logic: 'Radical de presque tous les poissons.' },
  { id: 'f-chong', hanzi: '虫', pinyin: 'chóng', fr: 'insecte / bestiole', cat: 'fondations',
    parts: [{ char: '虫', pinyin: 'chóng', meaning: 'pictogramme d\'un petit animal rampant', tag: 'forme' }],
    logic: 'Radical des insectes, mais aussi de pas mal de bestioles rampantes.' },

  // ---------------- ANIMAUX ----------------
  { id: 'a-ji', hanzi: '鸡', pinyin: 'jī', fr: 'poulet', cat: 'animaux', rad: '鸟',
    parts: [{ char: '又', pinyin: '(main)', meaning: 'trace de l\'ancien phonétique 奚', tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: 'oiseau', tag: 'sens' }],
    logic: 'oiseau + composant phonétique → poulet.' },
  { id: 'a-ya', hanzi: '鸭', pinyin: 'yā', fr: 'canard', cat: 'animaux', rad: '鸟',
    parts: [{ char: '甲', pinyin: 'jiǎ', meaning: 'carapace / n°1 (donne le son "ya")', tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: 'oiseau', tag: 'sens' }],
    logic: '甲(son) + 鸟(oiseau) → canard.' },
  { id: 'a-e', hanzi: '鹅', pinyin: 'é', fr: 'oie', cat: 'animaux', rad: '鸟',
    parts: [{ char: '我', pinyin: 'wǒ', meaning: '"moi" (donne le son "e")', tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: 'oiseau', tag: 'sens' }],
    logic: '我(son) + 鸟(oiseau) → oie.' },
  { id: 'a-ge', hanzi: '鸽', pinyin: 'gē', fr: 'pigeon', cat: 'animaux', rad: '鸟',
    parts: [{ char: '合', pinyin: 'hé', meaning: 'unir (donne le son "ge")', tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: 'oiseau', tag: 'sens' }],
    logic: '合(son) + 鸟(oiseau) → pigeon.' },
  { id: 'a-ying', hanzi: '鹰', pinyin: 'yīng', fr: 'aigle', cat: 'animaux', rad: '隹',
    parts: [{ char: '广', pinyin: '(toit)', meaning: 'évoque un promontoire / une falaise', tag: 'forme' }, { char: '隹', pinyin: 'zhuī', meaning: 'oiseau (forme ancienne)', tag: 'sens' }],
    logic: 'oiseau perché en hauteur → rapace.' },

  { id: 'a-jing', hanzi: '鲸', pinyin: 'jīng', fr: 'baleine', cat: 'animaux', rad: '鱼',
    parts: [{ char: '京', pinyin: 'jīng', meaning: 'capitale (donne le son "jing")', tag: 'son' }, { char: '鱼', pinyin: 'yú', meaning: 'poisson', tag: 'sens' }],
    logic: '京(son) + 鱼(poisson) → baleine (classée "poisson" à l\'ancienne).' },
  { id: 'a-li', hanzi: '鲤鱼', pinyin: 'lǐyú', fr: 'carpe', cat: 'animaux', rad: '鱼',
    parts: [{ char: '鲤', pinyin: 'lǐ', meaning: '里(intérieur, son) + 鱼(poisson)', tag: 'sens' }, { char: '鱼', pinyin: 'yú', meaning: 'poisson (répété, précise le mot)', tag: 'mot' }],
    logic: 'carpe + "poisson" en suffixe, comme beaucoup de noms de poissons.' },
  { id: 'a-sha', hanzi: '鲨鱼', pinyin: 'shāyú', fr: 'requin', cat: 'animaux', rad: '鱼',
    parts: [{ char: '鲨', pinyin: 'shā', meaning: '沙(sable, son) + 鱼(poisson)', tag: 'sens' }, { char: '鱼', pinyin: 'yú', meaning: 'poisson', tag: 'mot' }],
    logic: '"poisson-sable" + poisson → requin (vit près des fonds sableux).' },

  { id: 'a-mao', hanzi: '猫', pinyin: 'māo', fr: 'chat', cat: 'animaux', rad: '犭',
    parts: [{ char: '苗', pinyin: 'miáo', meaning: 'jeune pousse (donne le son "mao")', tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: 'animal 4 pattes', tag: 'sens' }],
    logic: '犭(mammifère) + 苗(son) → chat.' },
  { id: 'a-gou', hanzi: '狗', pinyin: 'gǒu', fr: 'chien', cat: 'animaux', rad: '犭',
    parts: [{ char: '句', pinyin: 'gōu/jù', meaning: 'phrase (donne le son "gou")', tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: 'animal 4 pattes', tag: 'sens' }],
    logic: '犭(mammifère) + 句(son) → chien.' },
  { id: 'a-hou', hanzi: '猴子', pinyin: 'hóuzi', fr: 'singe', cat: 'animaux', rad: '犭',
    parts: [{ char: '侯', pinyin: 'hóu', meaning: 'marquis (donne le son "hou")', tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: 'animal 4 pattes', tag: 'sens' }, { char: '子', pinyin: 'zi', meaning: 'suffixe neutre', tag: 'mot' }],
    logic: '犭(mammifère) + 侯(son) + 子(suffixe) → singe.' },
  { id: 'a-lang', hanzi: '狼', pinyin: 'láng', fr: 'loup', cat: 'animaux', rad: '犭',
    parts: [{ char: '良', pinyin: 'liáng', meaning: 'bon (donne le son "lang")', tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: 'animal 4 pattes', tag: 'sens' }],
    logic: '犭(mammifère) + 良(son) → loup.' },
  { id: 'a-zhu', hanzi: '猪', pinyin: 'zhū', fr: 'cochon', cat: 'animaux', rad: '豕',
    parts: [{ char: '者', pinyin: 'zhě', meaning: 'celui qui... (donne le son "zhu")', tag: 'son' }, { char: '豕', pinyin: 'shǐ', meaning: 'cochon (radical ancien, pas 犭!)', tag: 'sens' }],
    logic: 'Piège classique : le cochon utilise 豕, pas 犭.' },

  { id: 'a-mayi', hanzi: '蚂蚁', pinyin: 'mǎyǐ', fr: 'fourmi', cat: 'animaux', rad: '虫',
    parts: [{ char: '蚂', pinyin: 'mǎ', meaning: '马(cheval, son) + 虫(insecte)', tag: 'mot' }, { char: '蚁', pinyin: 'yǐ', meaning: '义(son) + 虫(insecte)', tag: 'mot' }],
    logic: 'Les deux caractères contiennent 虫 → sans surprise, ce sont des bestioles.' },
  { id: 'a-hudie', hanzi: '蝴蝶', pinyin: 'húdié', fr: 'papillon', cat: 'animaux', rad: '虫',
    parts: [{ char: '蝴', pinyin: 'hú', meaning: '胡(son) + 虫(insecte)', tag: 'mot' }, { char: '蝶', pinyin: 'dié', meaning: '枼(son) + 虫(insecte)', tag: 'mot' }],
    logic: 'Encore deux 虫 côte à côte → papillon.' },
  { id: 'a-mifeng', hanzi: '蜜蜂', pinyin: 'mìfēng', fr: 'abeille', cat: 'animaux', rad: '虫',
    parts: [{ char: '蜜', pinyin: 'mì', meaning: 'miel (contient 虫 tout en bas)', tag: 'mot' }, { char: '蜂', pinyin: 'fēng', meaning: '夆(son) + 虫(insecte)', tag: 'mot' }],
    logic: '"insecte du miel" → abeille.' },

  { id: 'a-huoji', hanzi: '火鸡', pinyin: 'huǒjī', fr: 'dinde', cat: 'animaux',
    parts: [{ char: '火', pinyin: 'huǒ', meaning: 'feu', tag: 'mot' }, { char: '鸡', pinyin: 'jī', meaning: 'poulet', tag: 'mot' }],
    logic: 'feu + poulet → littéralement "poulet de feu".', note: 'À cause de la ressemblance avec le dindon sauvage d\'Amérique, coloré comme des flammes.' },
  { id: 'a-xiongmao', hanzi: '熊猫', pinyin: 'xióngmāo', fr: 'panda', cat: 'animaux',
    parts: [{ char: '熊', pinyin: 'xióng', meaning: 'ours (le 灬 en bas = feu, pour les pattes)', tag: 'mot' }, { char: '猫', pinyin: 'māo', meaning: 'chat', tag: 'mot' }],
    logic: 'ours + chat → "chat-ours" = panda.' },
  { id: 'a-maotouying', hanzi: '猫头鹰', pinyin: 'māotóuyīng', fr: 'hibou / chouette', cat: 'animaux',
    parts: [{ char: '猫', pinyin: 'māo', meaning: 'chat', tag: 'mot' }, { char: '头', pinyin: 'tóu', meaning: 'tête', tag: 'mot' }, { char: '鹰', pinyin: 'yīng', meaning: 'aigle', tag: 'mot' }],
    logic: 'chat + tête + aigle → "aigle à tête de chat".', note: 'À cause des grands yeux ronds du hibou, comme un chat.' },
  { id: 'a-changjinglu', hanzi: '长颈鹿', pinyin: 'chángjǐnglù', fr: 'girafe', cat: 'animaux',
    parts: [{ char: '长', pinyin: 'cháng', meaning: 'long', tag: 'mot' }, { char: '颈', pinyin: 'jǐng', meaning: 'cou', tag: 'mot' }, { char: '鹿', pinyin: 'lù', meaning: 'cerf', tag: 'mot' }],
    logic: 'long + cou + cerf → "cerf à long cou" = girafe.' },
  { id: 'a-hema', hanzi: '河马', pinyin: 'hémǎ', fr: 'hippopotame', cat: 'animaux',
    parts: [{ char: '河', pinyin: 'hé', meaning: 'rivière', tag: 'mot' }, { char: '马', pinyin: 'mǎ', meaning: 'cheval', tag: 'mot' }],
    logic: 'rivière + cheval → "cheval de rivière" = hippopotame.' },
  { id: 'a-woniu', hanzi: '蜗牛', pinyin: 'wōniú', fr: 'escargot', cat: 'animaux',
    parts: [{ char: '蜗', pinyin: 'wō', meaning: 'spirale / coquille (contient 虫)', tag: 'mot' }, { char: '牛', pinyin: 'niú', meaning: 'bœuf / vache', tag: 'mot' }],
    logic: 'spirale + bœuf → "vache en spirale" = escargot.', note: '牛 sert ici à dire "gros animal lent", pas littéralement une vache.' },

  // ---------------- FRUITS ----------------
  { id: 'fr-pingguo', hanzi: '苹果', pinyin: 'píngguǒ', fr: 'pomme', cat: 'fruits', rad: '木',
    parts: [{ char: '苹', pinyin: 'píng', meaning: '艹(plante) + 平(son)', tag: 'mot' }, { char: '果', pinyin: 'guǒ', meaning: 'fruit — pictogramme d\'un fruit sur 木(arbre) !', tag: 'sens' }],
    logic: '果 est déjà "fruit sur un arbre" à lui seul → apparaît dans plein de noms de fruits.' },
  { id: 'fr-tao', hanzi: '桃', pinyin: 'táo', fr: 'pêche', cat: 'fruits', rad: '木',
    parts: [{ char: '木', pinyin: 'mù', meaning: 'arbre', tag: 'sens' }, { char: '兆', pinyin: 'zhào', meaning: 'présage (donne le son "tao")', tag: 'son' }],
    logic: '木(arbre) + 兆(son) → pêche.' },
  { id: 'fr-li', hanzi: '梨', pinyin: 'lí', fr: 'poire', cat: 'fruits', rad: '木',
    parts: [{ char: '利', pinyin: 'lì', meaning: 'tranchant / profit (donne le son "li")', tag: 'son' }, { char: '木', pinyin: 'mù', meaning: 'arbre', tag: 'sens' }],
    logic: '利(son) au-dessus de 木(arbre) → poire.' },
  { id: 'fr-cheng', hanzi: '橙子', pinyin: 'chéngzi', fr: 'orange', cat: 'fruits', rad: '木',
    parts: [{ char: '登', pinyin: 'dēng', meaning: 'monter (donne le son "cheng")', tag: 'son' }, { char: '木', pinyin: 'mù', meaning: 'arbre', tag: 'sens' }],
    logic: '木(arbre) + 登(son) → orange.' },
  { id: 'fr-shizi', hanzi: '柿子', pinyin: 'shìzi', fr: 'kaki', cat: 'fruits', rad: '木',
    parts: [{ char: '市', pinyin: 'shì', meaning: 'marché (donne le son "shi")', tag: 'son' }, { char: '木', pinyin: 'mù', meaning: 'arbre', tag: 'sens' }],
    logic: '木(arbre) + 市(son) → kaki.' },
  { id: 'fr-putao', hanzi: '葡萄', pinyin: 'pútáo', fr: 'raisin', cat: 'fruits', rad: '艹',
    parts: [{ char: '葡', pinyin: 'pú', meaning: '艹(plante) + 匍(son)', tag: 'mot' }, { char: '萄', pinyin: 'táo', meaning: '艹(plante) + 甸(son)', tag: 'mot' }],
    logic: 'Les deux caractères ne veulent rien dire séparément : mot emprunté phonétiquement (comme "kiwi" en français).', note: 'Vient probablement d\'un ancien mot d\'Asie centrale — comme 咖啡 (café) plus loin.' },
  { id: 'fr-boluo', hanzi: '菠萝', pinyin: 'bōluó', fr: 'ananas', cat: 'fruits', rad: '艹',
    parts: [{ char: '菠', pinyin: 'bō', meaning: '艹(plante) + 波(son, "vague")', tag: 'mot' }, { char: '萝', pinyin: 'luó', meaning: '艹(plante) + 罗(son)', tag: 'mot' }],
    logic: 'Deux 艹 côte à côte → sans surprise, c\'est une plante.' },
  { id: 'fr-xigua', hanzi: '西瓜', pinyin: 'xīguā', fr: 'pastèque', cat: 'fruits',
    parts: [{ char: '西', pinyin: 'xī', meaning: 'ouest', tag: 'mot' }, { char: '瓜', pinyin: 'guā', meaning: 'melon — pictogramme d\'un fruit sur une liane', tag: 'sens' }],
    logic: '"melon de l\'ouest" → importée depuis l\'ouest de la Chine il y a des siècles.' },
  { id: 'fr-caomei', hanzi: '草莓', pinyin: 'cǎoméi', fr: 'fraise', cat: 'fruits', rad: '艹',
    parts: [{ char: '草', pinyin: 'cǎo', meaning: 'herbe', tag: 'mot' }, { char: '莓', pinyin: 'méi', meaning: 'baie (contient 艹)', tag: 'mot' }],
    logic: 'herbe + baie → "baie d\'herbe" = fraise.' },

  // ---------------- LÉGUMES ----------------
  { id: 'l-xihongshi', hanzi: '西红柿', pinyin: 'xīhóngshì', fr: 'tomate', cat: 'legumes',
    parts: [{ char: '西', pinyin: 'xī', meaning: 'ouest', tag: 'mot' }, { char: '红', pinyin: 'hóng', meaning: 'rouge', tag: 'mot' }, { char: '柿', pinyin: 'shì', meaning: 'kaki (木 + 市)', tag: 'mot' }],
    logic: 'ouest + rouge + kaki → "kaki rouge de l\'ouest" = tomate.', note: 'Le classique pour expliquer la logique des mots composés chinois.' },
  { id: 'l-tudou', hanzi: '土豆', pinyin: 'tǔdòu', fr: 'pomme de terre', cat: 'legumes', rad: '土',
    parts: [{ char: '土', pinyin: 'tǔ', meaning: 'terre', tag: 'mot' }, { char: '豆', pinyin: 'dòu', meaning: 'haricot / pois', tag: 'mot' }],
    logic: 'terre + haricot → "haricot de terre" = pomme de terre.' },
  { id: 'l-huangguo', hanzi: '黄瓜', pinyin: 'huángguā', fr: 'concombre', cat: 'legumes',
    parts: [{ char: '黄', pinyin: 'huáng', meaning: 'jaune', tag: 'mot' }, { char: '瓜', pinyin: 'guā', meaning: 'melon', tag: 'mot' }],
    logic: 'jaune + melon → "melon jaune" = concombre.' },
  { id: 'l-baicai', hanzi: '白菜', pinyin: 'báicài', fr: 'chou chinois', cat: 'legumes', rad: '艹',
    parts: [{ char: '白', pinyin: 'bái', meaning: 'blanc', tag: 'mot' }, { char: '菜', pinyin: 'cài', meaning: 'légume (contient 艹)', tag: 'mot' }],
    logic: 'blanc + légume → "légume blanc" = chou chinois.' },
  { id: 'l-yangcong', hanzi: '洋葱', pinyin: 'yángcōng', fr: 'oignon', cat: 'legumes', rad: '艹',
    parts: [{ char: '洋', pinyin: 'yáng', meaning: 'océan / étranger (contient 氵eau)', tag: 'mot' }, { char: '葱', pinyin: 'cōng', meaning: 'ciboule (contient 艹)', tag: 'mot' }],
    logic: '"ciboule étrangère" → oignon, importé de l\'étranger.' },
  { id: 'l-huluobo', hanzi: '胡萝卜', pinyin: 'húluóbo', fr: 'carotte', cat: 'legumes', rad: '艹',
    parts: [{ char: '胡', pinyin: 'hú', meaning: 'préfixe "importé d\'Asie centrale"', tag: 'mot' }, { char: '萝卜', pinyin: 'luóbo', meaning: 'navet', tag: 'mot' }],
    logic: '"navet étranger" → carotte (le vrai navet, 萝卜, est local).' },
  { id: 'l-mogu', hanzi: '蘑菇', pinyin: 'mógu', fr: 'champignon', cat: 'legumes', rad: '艹',
    parts: [{ char: '蘑', pinyin: 'mó', meaning: '艹(plante) + 磨(son)', tag: 'mot' }, { char: '菇', pinyin: 'gū', meaning: '艹(plante) + 姑(son)', tag: 'mot' }],
    logic: 'Deux 艹 → encore une plante (même si un champignon n\'est pas vraiment une plante !).' },
  { id: 'l-lajiao', hanzi: '辣椒', pinyin: 'làjiāo', fr: 'piment', cat: 'legumes',
    parts: [{ char: '辣', pinyin: 'là', meaning: 'épicé / piquant', tag: 'mot' }, { char: '椒', pinyin: 'jiāo', meaning: 'épice à baies (contient 木)', tag: 'mot' }],
    logic: 'piquant + épice → piment.' },

  // ---------------- NOURRITURE ----------------
  { id: 'n-mifan', hanzi: '米饭', pinyin: 'mǐfàn', fr: 'riz cuit', cat: 'nourriture', rad: '米',
    parts: [{ char: '米', pinyin: 'mǐ', meaning: 'riz / grain', tag: 'mot' }, { char: '饭', pinyin: 'fàn', meaning: 'repas (contient 饣 nourriture)', tag: 'mot' }],
    logic: 'grain + repas → riz cuit, aussi le mot générique pour "repas".' },
  { id: 'n-miantiao', hanzi: '面条', pinyin: 'miàntiáo', fr: 'nouilles', cat: 'nourriture',
    parts: [{ char: '面', pinyin: 'miàn', meaning: 'farine / visage', tag: 'mot' }, { char: '条', pinyin: 'tiáo', meaning: 'bande / lanière', tag: 'mot' }],
    logic: 'farine + bande → nouilles.' },
  { id: 'n-jiaozi', hanzi: '饺子', pinyin: 'jiǎozi', fr: 'raviolis', cat: 'nourriture', rad: '饣',
    parts: [{ char: '饣', pinyin: 'shí', meaning: 'nourriture', tag: 'sens' }, { char: '交', pinyin: 'jiāo', meaning: 'croiser (donne le son "jiao")', tag: 'son' }, { char: '子', pinyin: 'zi', meaning: 'suffixe', tag: 'mot' }],
    logic: '饣(nourriture) + 交(son) → raviolis.' },
  { id: 'n-baozi', hanzi: '包子', pinyin: 'bāozi', fr: 'bun vapeur', cat: 'nourriture',
    parts: [{ char: '包', pinyin: 'bāo', meaning: 'envelopper — pictogramme d\'un paquet', tag: 'sens' }, { char: '子', pinyin: 'zi', meaning: 'suffixe', tag: 'mot' }],
    logic: '"chose enveloppée" → bun fourré cuit à la vapeur.' },
  { id: 'n-cha', hanzi: '茶', pinyin: 'chá', fr: 'thé', cat: 'nourriture', rad: '艹',
    parts: [{ char: '艹', pinyin: 'cǎo', meaning: 'plante', tag: 'sens' }, { char: '人', pinyin: 'rén', meaning: 'personne (au milieu)', tag: 'forme' }, { char: '木', pinyin: 'mù', meaning: 'arbre (en bas)', tag: 'sens' }],
    logic: 'une plante entre les mains d\'une personne, au-dessus d\'un arbre → le thé.' },
  { id: 'n-kafei', hanzi: '咖啡', pinyin: 'kāfēi', fr: 'café', cat: 'nourriture', rad: '口',
    parts: [{ char: '咖', pinyin: 'kā', meaning: '口(bouche, sens="on boit") + 加(son)', tag: 'mot' }, { char: '啡', pinyin: 'fēi', meaning: '口(bouche) + 非(son)', tag: 'mot' }],
    logic: 'Mot emprunté phonétiquement à "coffee" : les deux 口 signalent juste "ça se boit/dit", le son porte le sens.' },
  { id: 'n-niunai', hanzi: '牛奶', pinyin: 'niúnǎi', fr: 'lait', cat: 'nourriture',
    parts: [{ char: '牛', pinyin: 'niú', meaning: 'bœuf / vache', tag: 'mot' }, { char: '奶', pinyin: 'nǎi', meaning: 'lait (contient 女 femme : à l\'origine "sein nourricier")', tag: 'mot' }],
    logic: 'vache + lait(maternel) → lait de vache.' },
  { id: 'n-jidan', hanzi: '鸡蛋', pinyin: 'jīdàn', fr: 'œuf', cat: 'nourriture', rad: '鸟',
    parts: [{ char: '鸡', pinyin: 'jī', meaning: 'poulet', tag: 'mot' }, { char: '蛋', pinyin: 'dàn', meaning: 'œuf', tag: 'mot' }],
    logic: 'poulet + œuf → œuf de poule.' },

  // ---------------- PHRASES (par domaine) ----------------
  // Café
  { id: 'p-cafe1', hanzi: '你好，我要一杯咖啡。', pinyin: 'Nǐ hǎo, wǒ yào yì bēi kāfēi.', fr: 'Bonjour, je voudrais un café.', cat: 'phrases', domain: 'Café',
    parts: [{ char: '要', pinyin: 'yào', meaning: 'vouloir (verbe modal, direct devant le verbe/nom)', tag: 'mot' }, { char: '一杯', pinyin: 'yì bēi', meaning: '一(un) + 杯(classificateur "tasse/verre")', tag: 'mot' }, { char: '咖啡', pinyin: 'kāfēi', meaning: 'café (mot emprunté phonétiquement)', tag: 'mot' }],
    logic: 'Entre un nombre et un nom, il faut presque toujours un classificateur : 杯 pour ce qui se boit dans un verre/une tasse.' },
  { id: 'p-cafe2', hanzi: '可以加糖吗？', pinyin: 'Kěyǐ jiā táng ma?', fr: 'Je peux ajouter du sucre ?', cat: 'phrases', domain: 'Café',
    parts: [{ char: '可以', pinyin: 'kěyǐ', meaning: 'pouvoir / avoir la permission (verbe modal)', tag: 'mot' }, { char: '加', pinyin: 'jiā', meaning: 'ajouter', tag: 'mot' }, { char: '吗', pinyin: 'ma', meaning: 'particule finale = transforme en question oui/non', tag: 'mot' }],
    logic: '可以 se met directement devant le verbe, pas besoin de "to" comme en français/anglais.' },
  { id: 'p-cafe3', hanzi: '不要冰，谢谢。', pinyin: 'Bú yào bīng, xièxie.', fr: 'Pas de glace, merci.', cat: 'phrases', domain: 'Café',
    parts: [{ char: '不要', pinyin: 'bú yào', meaning: '不(négation) + 要(vouloir)', tag: 'mot' }, { char: '冰', pinyin: 'bīng', meaning: 'glace', tag: 'mot' }],
    logic: '不 négative directement le verbe modal 要.' },
  { id: 'p-cafe4', hanzi: '我要一个可颂和一杯拿铁。', pinyin: 'Wǒ yào yí gè kěsòng hé yì bēi nátiě.', fr: 'Je voudrais un croissant et un latte.', cat: 'phrases', domain: 'Café',
    parts: [{ char: '一个可颂', pinyin: 'yí gè kěsòng', meaning: 'un(classificateur générique 个) croissant', tag: 'mot' }, { char: '和', pinyin: 'hé', meaning: '"et" — relie deux groupes nominaux', tag: 'mot' }, { char: '一杯拿铁', pinyin: 'yì bēi nátiě', meaning: 'un(classificateur 杯) latte', tag: 'mot' }],
    logic: '和 relie ici deux groupes NOM+classificateur (même nature) → correct. Voir Grammaire pour la règle complète.' },
  { id: 'p-cafe5', hanzi: '谢谢，多少钱？', pinyin: 'Xièxie, duōshao qián?', fr: 'Merci, combien ça coûte ?', cat: 'phrases', domain: 'Café',
    parts: [{ char: '多少', pinyin: 'duōshao', meaning: 'combien (pour quantité ≥ à priori élevée)', tag: 'mot' }, { char: '钱', pinyin: 'qián', meaning: 'argent', tag: 'mot' }],
    logic: 'Littéralement "combien d\'argent ?".' },

  // Bavardage / gossip
  { id: 'p-gos1', hanzi: '你知道吗？', pinyin: 'Nǐ zhīdào ma?', fr: 'Tu sais quoi ?', cat: 'phrases', domain: 'Bavardage',
    parts: [{ char: '知道', pinyin: 'zhīdào', meaning: 'savoir', tag: 'mot' }, { char: '吗', pinyin: 'ma', meaning: 'particule question oui/non', tag: 'mot' }],
    logic: 'L\'accroche classique avant un ragot.' },
  { id: 'p-gos2', hanzi: '听说她换工作了。', pinyin: 'Tīngshuō tā huàn gōngzuò le.', fr: 'Il paraît qu\'elle a changé de travail.', cat: 'phrases', domain: 'Bavardage',
    parts: [{ char: '听说', pinyin: 'tīngshuō', meaning: 'littéralement "entendre dire" = il paraît que / on dit que', tag: 'mot' }, { char: '换工作', pinyin: 'huàn gōngzuò', meaning: 'changer de travail', tag: 'mot' }, { char: '了', pinyin: 'le', meaning: 'particule d\'action accomplie (pas "avoir" !)', tag: 'mot' }],
    logic: '了 en fin de phrase signale que l\'action a eu lieu / un changement d\'état — ce n\'est pas un auxiliaire comme "avoir".', note: '听说 est LE mot-clé pour rapporter un ragot en chinois.' },
  { id: 'p-gos3', hanzi: '真的假的？', pinyin: 'Zhēn de jiǎ de?', fr: 'Sérieux ?? (vrai ou faux ?)', cat: 'phrases', domain: 'Bavardage',
    parts: [{ char: '真的', pinyin: 'zhēn de', meaning: 'vrai', tag: 'mot' }, { char: '假的', pinyin: 'jiǎ de', meaning: 'faux', tag: 'mot' }],
    logic: 'Question "vrai (ou) faux ?" juxtaposée, très courant à l\'oral.' },
  { id: 'p-gos4', hanzi: '别告诉别人。', pinyin: 'Bié gàosu biérén.', fr: 'Ne le dis à personne.', cat: 'phrases', domain: 'Bavardage',
    parts: [{ char: '别', pinyin: 'bié', meaning: 'ne... pas (impératif négatif)', tag: 'mot' }, { char: '告诉', pinyin: 'gàosu', meaning: 'dire / informer', tag: 'mot' }, { char: '别人', pinyin: 'biérén', meaning: 'les autres / autrui', tag: 'mot' }],
    logic: '别 + verbe = ordre négatif ("ne fais pas...").' },
  { id: 'p-gos5', hanzi: '我也这么觉得。', pinyin: 'Wǒ yě zhème juéde.', fr: 'Je pense pareil.', cat: 'phrases', domain: 'Bavardage',
    parts: [{ char: '也', pinyin: 'yě', meaning: 'aussi (se place avant le verbe, pas après comme en français)', tag: 'mot' }, { char: '这么', pinyin: 'zhème', meaning: 'comme ça / ainsi', tag: 'mot' }, { char: '觉得', pinyin: 'juéde', meaning: 'penser / trouver que', tag: 'mot' }],
    logic: '也 se place toujours juste avant le verbe.' },

  // Transport
  { id: 'p-trans1', hanzi: '地铁站在哪儿？', pinyin: 'Dìtiě zhàn zài nǎr?', fr: 'Où est la station de métro ?', cat: 'phrases', domain: 'Transport',
    parts: [{ char: '地铁站', pinyin: 'dìtiě zhàn', meaning: 'station de métro', tag: 'mot' }, { char: '在', pinyin: 'zài', meaning: 'se trouver / être à', tag: 'mot' }, { char: '哪儿', pinyin: 'nǎr', meaning: 'où', tag: 'mot' }],
    logic: 'Structure fixe : [lieu] + 在 + 哪儿 pour demander un emplacement.' },
  { id: 'p-trans2', hanzi: '这张票多少钱？', pinyin: 'Zhè zhāng piào duōshao qián?', fr: 'Ce billet coûte combien ?', cat: 'phrases', domain: 'Transport',
    parts: [{ char: '这张票', pinyin: 'zhè zhāng piào', meaning: '这(ce) + 张(classificateur objets plats) + 票(billet)', tag: 'mot' }],
    logic: '张 classifie les objets plats et fins : billets, papiers, tickets.' },
  { id: 'p-trans3', hanzi: '下一站是什么？', pinyin: 'Xià yí zhàn shì shénme?', fr: 'Quelle est la prochaine station ?', cat: 'phrases', domain: 'Transport',
    parts: [{ char: '下一站', pinyin: 'xià yí zhàn', meaning: '下(suivant) + 一(un) + 站(station/arrêt)', tag: 'mot' }, { char: '是', pinyin: 'shì', meaning: 'être', tag: 'mot' }],
    logic: '下一 = "le suivant", très utile aussi pour "下一个" (le prochain, en général).' },
  { id: 'p-trans4', hanzi: '我要打车。', pinyin: 'Wǒ yào dǎchē.', fr: 'Je veux prendre un taxi.', cat: 'phrases', domain: 'Transport',
    parts: [{ char: '要', pinyin: 'yào', meaning: 'vouloir (modal)', tag: 'mot' }, { char: '打车', pinyin: 'dǎchē', meaning: 'littéralement "frapper une voiture" = héler un taxi', tag: 'mot' }],
    logic: '打 apparaît dans plein d\'expressions figées (打电话 téléphoner, 打球 jouer au ballon...) sans lien direct avec "frapper".' },

  // Politesse / base
  { id: 'p-pol1', hanzi: '很高兴认识你。', pinyin: 'Hěn gāoxìng rènshi nǐ.', fr: 'Ravi de te rencontrer.', cat: 'phrases', domain: 'Politesse',
    parts: [{ char: '很高兴', pinyin: 'hěn gāoxìng', meaning: 'très content (很 ne veut presque rien dire ici, obligatoire devant un adjectif seul)', tag: 'mot' }, { char: '认识', pinyin: 'rènshi', meaning: 'connaître / faire la connaissance de', tag: 'mot' }],
    logic: '很 devant un adjectif seul n\'est souvent qu\'une béquille grammaticale, pas un vrai "très".' },
  { id: 'p-pol2', hanzi: '对不起，我迟到了。', pinyin: 'Duìbuqǐ, wǒ chídào le.', fr: 'Désolé, je suis en retard.', cat: 'phrases', domain: 'Politesse',
    parts: [{ char: '对不起', pinyin: 'duìbuqǐ', meaning: 'désolé (litt. "je ne peux pas te faire face")', tag: 'mot' }, { char: '迟到', pinyin: 'chídào', meaning: 'arriver en retard', tag: 'mot' }, { char: '了', pinyin: 'le', meaning: 'accompli / état atteint', tag: 'mot' }],
    logic: '了 confirme que le retard est déjà un fait accompli.' },
  { id: 'p-pol3', hanzi: '没关系。', pinyin: 'Méi guānxi.', fr: 'Ce n\'est pas grave.', cat: 'phrases', domain: 'Politesse',
    parts: [{ char: '没', pinyin: 'méi', meaning: 'négation (utilisée avec 有 et certains états)', tag: 'mot' }, { char: '关系', pinyin: 'guānxi', meaning: 'relation / importance', tag: 'mot' }],
    logic: 'Littéralement "pas de relation/importance" → "aucun problème".' },
  { id: 'p-pol4', hanzi: '可以帮我一下吗？', pinyin: 'Kěyǐ bāng wǒ yíxià ma?', fr: 'Tu peux m\'aider un instant ?', cat: 'phrases', domain: 'Politesse',
    parts: [{ char: '可以', pinyin: 'kěyǐ', meaning: 'pouvoir (modal)', tag: 'mot' }, { char: '帮我', pinyin: 'bāng wǒ', meaning: 'aider moi (pas de préposition "à")', tag: 'mot' }, { char: '一下', pinyin: 'yíxià', meaning: 'un petit coup / un instant (adoucit la demande)', tag: 'mot' }],
    logic: '一下 après un verbe rend la demande plus légère, moins directe.' },
];

// ---------------- GRAMMAIRE : pièges & règles utiles ----------------
const GRAMMAR = [
  {
    id: 'g-he',
    title: '和 / 跟 ne relient que des mots de MÊME NATURE',
    rule: '和 (hé) et 跟 (gēn) veulent dire "et", mais seulement entre deux mots de même type : deux noms, deux pronoms, deux groupes nominaux. On ne les utilise JAMAIS pour relier deux verbes ou deux phrases.',
    examples: [
      { hanzi: '我和你', pinyin: 'wǒ hé nǐ', fr: 'toi et moi', ok: true, note: 'pronom + pronom' },
      { hanzi: '咖啡和茶', pinyin: 'kāfēi hé chá', fr: 'café et thé', ok: true, note: 'nom + nom' },
      { hanzi: '我吃和喝', pinyin: 'wǒ chī hé hē', fr: '(incorrect) "je mange et bois"', ok: false, note: '和 ne relie pas deux verbes' },
      { hanzi: '我吃饭，然后喝茶', pinyin: 'wǒ chīfàn, ránhòu hē chá', fr: 'je mange, puis je bois du thé', ok: true, note: 'pour enchaîner des actions → 然后 (ensuite), pas 和' },
    ],
  },
  {
    id: 'g-le',
    title: '了 marque un accompli, ce n\'est pas "avoir"',
    rule: '了 (le) placé après le verbe (ou en fin de phrase) signale qu\'une action est terminée ou qu\'un changement d\'état a eu lieu. Le verbe chinois ne se conjugue jamais — 了 n\'est pas un auxiliaire comme "avoir" en français, c\'est une particule d\'aspect.',
    examples: [
      { hanzi: '我吃了', pinyin: 'wǒ chī le', fr: 'j\'ai mangé', ok: true },
      { hanzi: '他走了', pinyin: 'tā zǒu le', fr: 'il est parti', ok: true },
      { hanzi: '我吃', pinyin: 'wǒ chī', fr: 'je mange (pas encore fini / habituel)', ok: true, note: 'sans 了, l\'action n\'est pas marquée comme terminée' },
    ],
  },
  {
    id: 'g-modaux',
    title: '可以 / 要 / 想 — les verbes modaux',
    rule: 'Un verbe modal se place directement devant le verbe principal, sans rien entre les deux (pas de "de" ni de "to"). 可以 (kěyǐ) = pouvoir/permission, 要 (yào) = vouloir/devoir, 想 (xiǎng) = avoir envie de.',
    examples: [
      { hanzi: '我要喝水', pinyin: 'wǒ yào hē shuǐ', fr: 'je veux boire de l\'eau', ok: true },
      { hanzi: '我可以走吗？', pinyin: 'wǒ kěyǐ zǒu ma?', fr: 'je peux partir ?', ok: true },
      { hanzi: '我想你', pinyin: 'wǒ xiǎng nǐ', fr: 'tu me manques (litt. "je pense à toi")', ok: true, note: '想 + personne = "penser à / manquer"' },
    ],
  },
  {
    id: 'g-classif',
    title: '量词 — les classificateurs (obligatoires !)',
    rule: 'Entre un nombre et un nom, il faut presque toujours un classificateur — comme "une TRANCHE de pain" en français, mais quasi systématique en chinois. Chaque catégorie d\'objet a le sien : 个 (gè) générique, 杯 (bēi) pour les boissons servies, 张 (zhāng) pour les objets plats, 只 (zhī) pour les animaux.',
    examples: [
      { hanzi: '一个人', pinyin: 'yí gè rén', fr: 'une personne', ok: true, note: '个 = générique, à utiliser par défaut' },
      { hanzi: '一杯咖啡', pinyin: 'yì bēi kāfēi', fr: 'un café', ok: true, note: '杯 = ce qui se sert dans une tasse/un verre' },
      { hanzi: '两张票', pinyin: 'liǎng zhāng piào', fr: 'deux billets', ok: true, note: '张 = objets plats et fins' },
      { hanzi: '一咖啡', pinyin: 'yì kāfēi', fr: '(incorrect, classificateur manquant)', ok: false },
    ],
  },
];

const TAG_LABEL = {
  sens: 'sens',
  son: 'son',
  mot: 'mot',
  forme: 'forme',
};

// Emoji indexés par caractère(s) — utilisé pour les cartes, la décomposition
// et les radicaux. Sert d'ancrage visuel + rend la logique des mots composés
// immédiatement lisible (ex: 火🔥 + 鸡🐔 → 火鸡🦃).
const EMOJI = {
  // radicaux / fondations
  '木': '🌳', '艹': '🌿', '氵': '💧', '水': '💧', '火': '🔥', '灬': '🔥',
  '土': '🟫', '金': '🪙', '鸟': '🐦', '隹': '🐦', '犭': '🐾', '鱼': '🐟',
  '虫': '🐛', '豕': '🐖', '饣': '🍽️', '米': '🌾', '口': '👄', '女': '👩',
  '子': '🧒', '人': '🧍', '日': '☀️', '月': '🌙', '山': '⛰️',
  // couleurs / directions qui reviennent dans les mots composés
  '红': '🔴', '黄': '🟡', '白': '⚪', '西': '🧭',
  // animaux
  '鸡': '🐔', '鸭': '🦆', '鹅': '🦢', '鸽': '🕊️', '鹰': '🦅', '鲸': '🐋',
  '鲤鱼': '🐟', '鲨鱼': '🦈', '猫': '🐱', '狗': '🐶', '猴子': '🐒', '狼': '🐺',
  '猪': '🐷', '蚂蚁': '🐜', '蝴蝶': '🦋', '蜜蜂': '🐝', '牛': '🐮', '鹿': '🦌',
  '火鸡': '🦃', '熊猫': '🐼', '熊': '🐻', '猫头鹰': '🦉', '长颈鹿': '🦒',
  '河马': '🦛', '蜗牛': '🐌',
  // fruits
  '苹果': '🍎', '果': '🍏', '桃': '🍑', '梨': '🍐', '橙子': '🍊', '柿子': '🟠',
  '葡萄': '🍇', '菠萝': '🍍', '西瓜': '🍉', '草莓': '🍓', '瓜': '🍈',
  // légumes
  '西红柿': '🍅', '土豆': '🥔', '黄瓜': '🥒', '白菜': '🥬', '洋葱': '🧅',
  '胡萝卜': '🥕', '豆': '🫘', '蘑菇': '🍄', '辣椒': '🌶️',
  // nourriture / boissons
  '米饭': '🍚', '面条': '🍜', '饺子': '🥟', '包子': '🥯', '茶': '🍵',
  '咖啡': '☕', '牛奶': '🥛', '鸡蛋': '🥚',
};
