// ============================================================
// WOSHICND — Données : radicaux clés + vocabulaire décomposé
// Tout le texte traduisible est bilingue : { fr: '...', en: '...' }
// ============================================================

// Radicaux "fondations" : les briques qui reviennent partout.
// Servent de base ET de filtre croisé (clique un radical → tous les mots qui le contiennent)
const RADICALS = {
  '木': { pinyin: 'mù', meaning: { fr: 'bois / arbre', en: 'wood / tree' }, family: 'nature' },
  '艹': { pinyin: 'cǎo', meaning: { fr: 'plante / herbe', en: 'plant / grass' }, family: 'nature' },
  '氵': { pinyin: 'shuǐ', meaning: { fr: 'eau', en: 'water' }, family: 'nature' },
  '火': { pinyin: 'huǒ', meaning: { fr: 'feu', en: 'fire' }, family: 'nature' },
  '灬': { pinyin: 'huǒ', meaning: { fr: 'feu (variante basse)', en: 'fire (bottom variant)' }, family: 'nature' },
  '土': { pinyin: 'tǔ', meaning: { fr: 'terre', en: 'earth' }, family: 'nature' },
  '金': { pinyin: 'jīn', meaning: { fr: 'métal / or', en: 'metal / gold' }, family: 'nature' },
  '鸟': { pinyin: 'niǎo', meaning: { fr: 'oiseau', en: 'bird' }, family: 'animal' },
  '隹': { pinyin: 'zhuī', meaning: { fr: 'oiseau (forme ancienne)', en: 'bird (ancient form)' }, family: 'animal' },
  '犭': { pinyin: 'quǎn', meaning: { fr: 'animal à 4 pattes (chien)', en: 'four-legged animal (dog)' }, family: 'animal' },
  '鱼': { pinyin: 'yú', meaning: { fr: 'poisson', en: 'fish' }, family: 'animal' },
  '虫': { pinyin: 'chóng', meaning: { fr: 'insecte / bestiole', en: 'insect / critter' }, family: 'animal' },
  '豕': { pinyin: 'shǐ', meaning: { fr: 'cochon', en: 'pig' }, family: 'animal' },
  '饣': { pinyin: 'shí', meaning: { fr: 'nourriture', en: 'food' }, family: 'nourriture' },
  '米': { pinyin: 'mǐ', meaning: { fr: 'riz / grain', en: 'rice / grain' }, family: 'nourriture' },
  '口': { pinyin: 'kǒu', meaning: { fr: 'bouche', en: 'mouth' }, family: 'corps' },
  '女': { pinyin: 'nǚ', meaning: { fr: 'femme', en: 'woman' }, family: 'autre' },
  '子': { pinyin: 'zǐ', meaning: { fr: 'enfant', en: 'child' }, family: 'autre' },
  '人': { pinyin: 'rén', meaning: { fr: 'personne', en: 'person' }, family: 'autre' },
  '日': { pinyin: 'rì', meaning: { fr: 'soleil / jour', en: 'sun / day' }, family: 'nature' },
  '月': { pinyin: 'yuè', meaning: { fr: 'lune / mois / chair', en: 'moon / month / flesh' }, family: 'nature' },
  '山': { pinyin: 'shān', meaning: { fr: 'montagne', en: 'mountain' }, family: 'nature' },
};

// Catégories affichées dans le menu, dans l'ordre
const CATEGORIES = [
  { id: 'fondations', label: { fr: 'Fondations', en: 'Foundations' }, sub: { fr: 'LES BRIQUES DE BASE', en: 'CORE BUILDING BLOCKS' } },
  { id: 'animaux', label: { fr: 'Animaux', en: 'Animals' }, sub: { fr: '动物 · DŌNGWÙ', en: '动物 · DŌNGWÙ' } },
  { id: 'fruits', label: { fr: 'Fruits', en: 'Fruits' }, sub: { fr: '水果 · SHUǏGUǑ', en: '水果 · SHUǏGUǑ' } },
  { id: 'legumes', label: { fr: 'Légumes', en: 'Vegetables' }, sub: { fr: '蔬菜 · SHŪCÀI', en: '蔬菜 · SHŪCÀI' } },
  { id: 'nourriture', label: { fr: 'Nourriture', en: 'Food' }, sub: { fr: '食物 · SHÍWÙ', en: '食物 · SHÍWÙ' } },
  { id: 'phrases', label: { fr: 'Phrases', en: 'Phrases' }, sub: { fr: '日常用语 · PAR DOMAINE', en: '日常用语 · BY TOPIC' } },
  { id: 'grammaire', label: { fr: 'Grammaire', en: 'Grammar' }, sub: { fr: 'PIÈGES & CONNECTEURS', en: 'TRAPS & CONNECTORS' } },
  { id: 'ecriture', label: { fr: 'Écriture', en: 'Writing' }, sub: { fr: '写字 · TRACÉ AU DOIGT', en: '写字 · TRACE WITH YOUR FINGER' } },
  { id: 'explorer', label: { fr: 'Explorer', en: 'Explore' }, sub: { fr: 'RÉSEAU DE MOTS', en: 'WORD NETWORK' } },
  { id: 'radicaux', label: { fr: 'Radicaux', en: 'Radicals' }, sub: { fr: 'VUE CROISÉE', en: 'CROSS-REFERENCE' } },
  { id: 'revision', label: { fr: 'Révision', en: 'Review' }, sub: { fr: 'FLASHCARDS', en: 'FLASHCARDS' } },
];

// tag: 'sens' (radical de sens), 'son' (composant phonétique), 'mot' (caractère = mot complet dans un mot composé), 'forme' (pictogramme)
const VOCAB = [
  // ---------------- FONDATIONS ----------------
  { id: 'f-mu', hanzi: '木', pinyin: 'mù', gloss: { fr: 'bois / arbre', en: 'wood / tree' }, cat: 'fondations',
    parts: [{ char: '木', pinyin: 'mù', meaning: { fr: 'pictogramme d\'un arbre (tronc + branches + racines)', en: 'pictogram of a tree (trunk + branches + roots)' }, tag: 'forme' }],
    logic: { fr: 'Pictogramme direct : un arbre stylisé.', en: 'Direct pictogram: a stylized tree.' } },
  { id: 'f-cao', hanzi: '艹', pinyin: 'cǎo', gloss: { fr: 'herbe / plante (radical)', en: 'grass / plant (radical)' }, cat: 'fondations',
    parts: [{ char: '艹', pinyin: 'cǎo', meaning: { fr: 'deux brins d\'herbe qui poussent', en: 'two blades of grass growing' }, tag: 'forme' }],
    logic: { fr: 'Toujours en haut d\'un caractère → indique un lien avec les plantes.', en: 'Always at the top of a character → signals a link to plants.' } },
  { id: 'f-shui', hanzi: '水', pinyin: 'shuǐ', gloss: { fr: 'eau', en: 'water' }, cat: 'fondations',
    parts: [{ char: '水', pinyin: 'shuǐ', meaning: { fr: 'pictogramme d\'un courant d\'eau', en: 'pictogram of a water current' }, tag: 'forme' }],
    logic: { fr: 'Devient 氵 (3 gouttes) quand il est sur le côté gauche d\'un caractère.', en: 'Becomes 氵 (3 drops) when placed on the left side of a character.' } },
  { id: 'f-huo', hanzi: '火', pinyin: 'huǒ', gloss: { fr: 'feu', en: 'fire' }, cat: 'fondations',
    parts: [{ char: '火', pinyin: 'huǒ', meaning: { fr: 'pictogramme de flammes', en: 'pictogram of flames' }, tag: 'forme' }],
    logic: { fr: 'Devient 灬 (4 points) quand il est en bas d\'un caractère.', en: 'Becomes 灬 (4 dots) when placed at the bottom of a character.' } },
  { id: 'f-tu', hanzi: '土', pinyin: 'tǔ', gloss: { fr: 'terre', en: 'earth' }, cat: 'fondations',
    parts: [{ char: '土', pinyin: 'tǔ', meaning: { fr: 'un tas de terre posé au sol', en: 'a mound of earth on the ground' }, tag: 'forme' }],
    logic: { fr: 'Pictogramme d\'un monticule de terre.', en: 'Pictogram of a mound of earth.' } },
  { id: 'f-jin', hanzi: '金', pinyin: 'jīn', gloss: { fr: 'métal / or', en: 'metal / gold' }, cat: 'fondations',
    parts: [{ char: '金', pinyin: 'jīn', meaning: { fr: 'pépites de métal dans la terre', en: 'metal nuggets in the ground' }, tag: 'forme' }],
    logic: { fr: 'Devient 钅 sur le côté gauche d\'un caractère (objets en métal).', en: 'Becomes 钅 on the left side of a character (metal objects).' } },
  { id: 'f-niao', hanzi: '鸟', pinyin: 'niǎo', gloss: { fr: 'oiseau', en: 'bird' }, cat: 'fondations',
    parts: [{ char: '鸟', pinyin: 'niǎo', meaning: { fr: 'pictogramme d\'un oiseau (tête, aile, queue)', en: 'pictogram of a bird (head, wing, tail)' }, tag: 'forme' }],
    logic: { fr: 'Radical présent dans quasi tous les noms d\'oiseaux.', en: 'Radical found in almost every bird name.' } },
  { id: 'f-quan', hanzi: '犭', pinyin: 'quǎn', gloss: { fr: 'animal à 4 pattes (radical)', en: 'four-legged animal (radical)' }, cat: 'fondations',
    parts: [{ char: '犭', pinyin: 'quǎn', meaning: { fr: 'forme raccourcie de 犬 (chien)', en: 'shortened form of 犬 (dog)' }, tag: 'forme' }],
    logic: { fr: 'Toujours à gauche → signale un mammifère à 4 pattes.', en: 'Always on the left → signals a four-legged mammal.' } },
  { id: 'f-yu', hanzi: '鱼', pinyin: 'yú', gloss: { fr: 'poisson', en: 'fish' }, cat: 'fondations',
    parts: [{ char: '鱼', pinyin: 'yú', meaning: { fr: 'pictogramme d\'un poisson (tête, écailles, queue)', en: 'pictogram of a fish (head, scales, tail)' }, tag: 'forme' }],
    logic: { fr: 'Radical de presque tous les poissons.', en: 'Radical found in almost every fish name.' } },
  { id: 'f-chong', hanzi: '虫', pinyin: 'chóng', gloss: { fr: 'insecte / bestiole', en: 'insect / critter' }, cat: 'fondations',
    parts: [{ char: '虫', pinyin: 'chóng', meaning: { fr: 'pictogramme d\'un petit animal rampant', en: 'pictogram of a small crawling creature' }, tag: 'forme' }],
    logic: { fr: 'Radical des insectes, mais aussi de pas mal de bestioles rampantes.', en: 'Radical for insects, but also plenty of other crawling critters.' } },

  // ---------------- ANIMAUX ----------------
  { id: 'a-ji', hanzi: '鸡', pinyin: 'jī', gloss: { fr: 'poulet', en: 'chicken' }, cat: 'animaux', rad: '鸟',
    parts: [{ char: '又', pinyin: '(main)', meaning: { fr: 'trace de l\'ancien phonétique 奚', en: 'trace of the old phonetic component 奚' }, tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: { fr: 'oiseau', en: 'bird' }, tag: 'sens' }],
    logic: { fr: 'oiseau + composant phonétique → poulet.', en: 'bird + phonetic component → chicken.' } },
  { id: 'a-ya', hanzi: '鸭', pinyin: 'yā', gloss: { fr: 'canard', en: 'duck' }, cat: 'animaux', rad: '鸟',
    parts: [{ char: '甲', pinyin: 'jiǎ', meaning: { fr: 'carapace / n°1 (donne le son "ya")', en: 'shell / #1 (gives the sound "ya")' }, tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: { fr: 'oiseau', en: 'bird' }, tag: 'sens' }],
    logic: { fr: '甲(son) + 鸟(oiseau) → canard.', en: '甲(sound) + 鸟(bird) → duck.' } },
  { id: 'a-e', hanzi: '鹅', pinyin: 'é', gloss: { fr: 'oie', en: 'goose' }, cat: 'animaux', rad: '鸟',
    parts: [{ char: '我', pinyin: 'wǒ', meaning: { fr: '"moi" (donne le son "e")', en: '"me" (gives the sound "e")' }, tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: { fr: 'oiseau', en: 'bird' }, tag: 'sens' }],
    logic: { fr: '我(son) + 鸟(oiseau) → oie.', en: '我(sound) + 鸟(bird) → goose.' } },
  { id: 'a-ge', hanzi: '鸽', pinyin: 'gē', gloss: { fr: 'pigeon', en: 'pigeon' }, cat: 'animaux', rad: '鸟',
    parts: [{ char: '合', pinyin: 'hé', meaning: { fr: 'unir (donne le son "ge")', en: 'to unite (gives the sound "ge")' }, tag: 'son' }, { char: '鸟', pinyin: 'niǎo', meaning: { fr: 'oiseau', en: 'bird' }, tag: 'sens' }],
    logic: { fr: '合(son) + 鸟(oiseau) → pigeon.', en: '合(sound) + 鸟(bird) → pigeon.' } },
  { id: 'a-ying', hanzi: '鹰', pinyin: 'yīng', gloss: { fr: 'aigle', en: 'eagle' }, cat: 'animaux', rad: '隹',
    parts: [{ char: '广', pinyin: '(toit)', meaning: { fr: 'évoque un promontoire / une falaise', en: 'evokes a cliff / a promontory' }, tag: 'forme' }, { char: '隹', pinyin: 'zhuī', meaning: { fr: 'oiseau (forme ancienne)', en: 'bird (ancient form)' }, tag: 'sens' }],
    logic: { fr: 'oiseau perché en hauteur → rapace.', en: 'bird perched up high → bird of prey.' } },

  { id: 'a-jing', hanzi: '鲸', pinyin: 'jīng', gloss: { fr: 'baleine', en: 'whale' }, cat: 'animaux', rad: '鱼',
    parts: [{ char: '京', pinyin: 'jīng', meaning: { fr: 'capitale (donne le son "jing")', en: 'capital city (gives the sound "jing")' }, tag: 'son' }, { char: '鱼', pinyin: 'yú', meaning: { fr: 'poisson', en: 'fish' }, tag: 'sens' }],
    logic: { fr: '京(son) + 鱼(poisson) → baleine (classée "poisson" à l\'ancienne).', en: '京(sound) + 鱼(fish) → whale (classified as a "fish" in old taxonomy).' } },
  { id: 'a-li', hanzi: '鲤鱼', pinyin: 'lǐyú', gloss: { fr: 'carpe', en: 'carp' }, cat: 'animaux', rad: '鱼',
    parts: [{ char: '鲤', pinyin: 'lǐ', meaning: { fr: '里(intérieur, son) + 鱼(poisson)', en: '里(inside, sound) + 鱼(fish)' }, tag: 'sens' }, { char: '鱼', pinyin: 'yú', meaning: { fr: 'poisson (répété, précise le mot)', en: 'fish (repeated, clarifies the word)' }, tag: 'mot' }],
    logic: { fr: 'carpe + "poisson" en suffixe, comme beaucoup de noms de poissons.', en: 'carp + "fish" as a suffix, like many fish names.' } },
  { id: 'a-sha', hanzi: '鲨鱼', pinyin: 'shāyú', gloss: { fr: 'requin', en: 'shark' }, cat: 'animaux', rad: '鱼',
    parts: [{ char: '鲨', pinyin: 'shā', meaning: { fr: '沙(sable, son) + 鱼(poisson)', en: '沙(sand, sound) + 鱼(fish)' }, tag: 'sens' }, { char: '鱼', pinyin: 'yú', meaning: { fr: 'poisson', en: 'fish' }, tag: 'mot' }],
    logic: { fr: '"poisson-sable" + poisson → requin (vit près des fonds sableux).', en: '"sand-fish" + fish → shark (lives near sandy seabeds).' } },

  { id: 'a-mao', hanzi: '猫', pinyin: 'māo', gloss: { fr: 'chat', en: 'cat' }, cat: 'animaux', rad: '犭',
    parts: [{ char: '苗', pinyin: 'miáo', meaning: { fr: 'jeune pousse (donne le son "mao")', en: 'young sprout (gives the sound "mao")' }, tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: { fr: 'animal 4 pattes', en: 'four-legged animal' }, tag: 'sens' }],
    logic: { fr: '犭(mammifère) + 苗(son) → chat.', en: '犭(mammal) + 苗(sound) → cat.' } },
  { id: 'a-gou', hanzi: '狗', pinyin: 'gǒu', gloss: { fr: 'chien', en: 'dog' }, cat: 'animaux', rad: '犭',
    parts: [{ char: '句', pinyin: 'gōu/jù', meaning: { fr: 'phrase (donne le son "gou")', en: 'sentence (gives the sound "gou")' }, tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: { fr: 'animal 4 pattes', en: 'four-legged animal' }, tag: 'sens' }],
    logic: { fr: '犭(mammifère) + 句(son) → chien.', en: '犭(mammal) + 句(sound) → dog.' } },
  { id: 'a-hou', hanzi: '猴子', pinyin: 'hóuzi', gloss: { fr: 'singe', en: 'monkey' }, cat: 'animaux', rad: '犭',
    parts: [{ char: '侯', pinyin: 'hóu', meaning: { fr: 'marquis (donne le son "hou")', en: 'marquis (gives the sound "hou")' }, tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: { fr: 'animal 4 pattes', en: 'four-legged animal' }, tag: 'sens' }, { char: '子', pinyin: 'zi', meaning: { fr: 'suffixe neutre', en: 'neutral suffix' }, tag: 'mot' }],
    logic: { fr: '犭(mammifère) + 侯(son) + 子(suffixe) → singe.', en: '犭(mammal) + 侯(sound) + 子(suffix) → monkey.' } },
  { id: 'a-lang', hanzi: '狼', pinyin: 'láng', gloss: { fr: 'loup', en: 'wolf' }, cat: 'animaux', rad: '犭',
    parts: [{ char: '良', pinyin: 'liáng', meaning: { fr: 'bon (donne le son "lang")', en: 'good (gives the sound "lang")' }, tag: 'son' }, { char: '犭', pinyin: 'quǎn', meaning: { fr: 'animal 4 pattes', en: 'four-legged animal' }, tag: 'sens' }],
    logic: { fr: '犭(mammifère) + 良(son) → loup.', en: '犭(mammal) + 良(sound) → wolf.' } },
  { id: 'a-zhu', hanzi: '猪', pinyin: 'zhū', gloss: { fr: 'cochon', en: 'pig' }, cat: 'animaux', rad: '豕',
    parts: [{ char: '者', pinyin: 'zhě', meaning: { fr: 'celui qui... (donne le son "zhu")', en: 'the one who... (gives the sound "zhu")' }, tag: 'son' }, { char: '豕', pinyin: 'shǐ', meaning: { fr: 'cochon (radical ancien, pas 犭!)', en: 'pig (ancient radical, not 犭!)' }, tag: 'sens' }],
    logic: { fr: 'Piège classique : le cochon utilise 豕, pas 犭.', en: 'Classic trap: pig uses 豕, not 犭.' } },

  { id: 'a-mayi', hanzi: '蚂蚁', pinyin: 'mǎyǐ', gloss: { fr: 'fourmi', en: 'ant' }, cat: 'animaux', rad: '虫',
    parts: [{ char: '蚂', pinyin: 'mǎ', meaning: { fr: '马(cheval, son) + 虫(insecte)', en: '马(horse, sound) + 虫(insect)' }, tag: 'mot' }, { char: '蚁', pinyin: 'yǐ', meaning: { fr: '义(son) + 虫(insecte)', en: '义(sound) + 虫(insect)' }, tag: 'mot' }],
    logic: { fr: 'Les deux caractères contiennent 虫 → sans surprise, ce sont des bestioles.', en: 'Both characters contain 虫 → no surprise, they\'re critters.' } },
  { id: 'a-hudie', hanzi: '蝴蝶', pinyin: 'húdié', gloss: { fr: 'papillon', en: 'butterfly' }, cat: 'animaux', rad: '虫',
    parts: [{ char: '蝴', pinyin: 'hú', meaning: { fr: '胡(son) + 虫(insecte)', en: '胡(sound) + 虫(insect)' }, tag: 'mot' }, { char: '蝶', pinyin: 'dié', meaning: { fr: '枼(son) + 虫(insecte)', en: '枼(sound) + 虫(insect)' }, tag: 'mot' }],
    logic: { fr: 'Encore deux 虫 côte à côte → papillon.', en: 'Two more 虫 side by side → butterfly.' } },
  { id: 'a-mifeng', hanzi: '蜜蜂', pinyin: 'mìfēng', gloss: { fr: 'abeille', en: 'bee' }, cat: 'animaux', rad: '虫',
    parts: [{ char: '蜜', pinyin: 'mì', meaning: { fr: 'miel (contient 虫 tout en bas)', en: 'honey (contains 虫 at the very bottom)' }, tag: 'mot' }, { char: '蜂', pinyin: 'fēng', meaning: { fr: '夆(son) + 虫(insecte)', en: '夆(sound) + 虫(insect)' }, tag: 'mot' }],
    logic: { fr: '"insecte du miel" → abeille.', en: '"honey insect" → bee.' } },

  { id: 'a-huoji', hanzi: '火鸡', pinyin: 'huǒjī', gloss: { fr: 'dinde', en: 'turkey' }, cat: 'animaux',
    parts: [{ char: '火', pinyin: 'huǒ', meaning: { fr: 'feu', en: 'fire' }, tag: 'mot' }, { char: '鸡', pinyin: 'jī', meaning: { fr: 'poulet', en: 'chicken' }, tag: 'mot' }],
    logic: { fr: 'feu + poulet → littéralement "poulet de feu".', en: 'fire + chicken → literally "fire chicken".' },
    note: { fr: 'À cause de la ressemblance avec le dindon sauvage d\'Amérique, coloré comme des flammes.', en: 'Because of its resemblance to the wild American turkey, colored like flames.' } },
  { id: 'a-xiongmao', hanzi: '熊猫', pinyin: 'xióngmāo', gloss: { fr: 'panda', en: 'panda' }, cat: 'animaux',
    parts: [{ char: '熊', pinyin: 'xióng', meaning: { fr: 'ours (le 灬 en bas = feu, pour les pattes)', en: 'bear (the 灬 at the bottom = fire, for the paws)' }, tag: 'mot' }, { char: '猫', pinyin: 'māo', meaning: { fr: 'chat', en: 'cat' }, tag: 'mot' }],
    logic: { fr: 'ours + chat → "chat-ours" = panda.', en: 'bear + cat → "cat-bear" = panda.' } },
  { id: 'a-maotouying', hanzi: '猫头鹰', pinyin: 'māotóuyīng', gloss: { fr: 'hibou / chouette', en: 'owl' }, cat: 'animaux',
    parts: [{ char: '猫', pinyin: 'māo', meaning: { fr: 'chat', en: 'cat' }, tag: 'mot' }, { char: '头', pinyin: 'tóu', meaning: { fr: 'tête', en: 'head' }, tag: 'mot' }, { char: '鹰', pinyin: 'yīng', meaning: { fr: 'aigle', en: 'eagle' }, tag: 'mot' }],
    logic: { fr: 'chat + tête + aigle → "aigle à tête de chat".', en: 'cat + head + eagle → "cat-headed eagle".' },
    note: { fr: 'À cause des grands yeux ronds du hibou, comme un chat.', en: 'Because of the owl\'s big round eyes, like a cat.' } },
  { id: 'a-changjinglu', hanzi: '长颈鹿', pinyin: 'chángjǐnglù', gloss: { fr: 'girafe', en: 'giraffe' }, cat: 'animaux',
    parts: [{ char: '长', pinyin: 'cháng', meaning: { fr: 'long', en: 'long' }, tag: 'mot' }, { char: '颈', pinyin: 'jǐng', meaning: { fr: 'cou', en: 'neck' }, tag: 'mot' }, { char: '鹿', pinyin: 'lù', meaning: { fr: 'cerf', en: 'deer' }, tag: 'mot' }],
    logic: { fr: 'long + cou + cerf → "cerf à long cou" = girafe.', en: 'long + neck + deer → "long-necked deer" = giraffe.' } },
  { id: 'a-hema', hanzi: '河马', pinyin: 'hémǎ', gloss: { fr: 'hippopotame', en: 'hippopotamus' }, cat: 'animaux',
    parts: [{ char: '河', pinyin: 'hé', meaning: { fr: 'rivière', en: 'river' }, tag: 'mot' }, { char: '马', pinyin: 'mǎ', meaning: { fr: 'cheval', en: 'horse' }, tag: 'mot' }],
    logic: { fr: 'rivière + cheval → "cheval de rivière" = hippopotame.', en: 'river + horse → "river horse" = hippopotamus.' } },
  { id: 'a-woniu', hanzi: '蜗牛', pinyin: 'wōniú', gloss: { fr: 'escargot', en: 'snail' }, cat: 'animaux',
    parts: [{ char: '蜗', pinyin: 'wō', meaning: { fr: 'spirale / coquille (contient 虫)', en: 'spiral / shell (contains 虫)' }, tag: 'mot' }, { char: '牛', pinyin: 'niú', meaning: { fr: 'bœuf / vache', en: 'ox / cow' }, tag: 'mot' }],
    logic: { fr: 'spirale + bœuf → "vache en spirale" = escargot.', en: 'spiral + ox → "spiral cow" = snail.' },
    note: { fr: '牛 sert ici à dire "gros animal lent", pas littéralement une vache.', en: '牛 here just means "big slow creature", not literally a cow.' } },

  // ---------------- FRUITS ----------------
  { id: 'fr-pingguo', hanzi: '苹果', pinyin: 'píngguǒ', gloss: { fr: 'pomme', en: 'apple' }, cat: 'fruits', rad: '木',
    parts: [{ char: '苹', pinyin: 'píng', meaning: { fr: '艹(plante) + 平(son)', en: '艹(plant) + 平(sound)' }, tag: 'mot' }, { char: '果', pinyin: 'guǒ', meaning: { fr: 'fruit — pictogramme d\'un fruit sur 木(arbre) !', en: 'fruit — pictogram of a fruit on 木(a tree)!' }, tag: 'sens' }],
    logic: { fr: '果 est déjà "fruit sur un arbre" à lui seul → apparaît dans plein de noms de fruits.', en: '果 already means "fruit on a tree" by itself → shows up in tons of fruit names.' } },
  { id: 'fr-tao', hanzi: '桃', pinyin: 'táo', gloss: { fr: 'pêche', en: 'peach' }, cat: 'fruits', rad: '木',
    parts: [{ char: '木', pinyin: 'mù', meaning: { fr: 'arbre', en: 'tree' }, tag: 'sens' }, { char: '兆', pinyin: 'zhào', meaning: { fr: 'présage (donne le son "tao")', en: 'omen (gives the sound "tao")' }, tag: 'son' }],
    logic: { fr: '木(arbre) + 兆(son) → pêche.', en: '木(tree) + 兆(sound) → peach.' } },
  { id: 'fr-li', hanzi: '梨', pinyin: 'lí', gloss: { fr: 'poire', en: 'pear' }, cat: 'fruits', rad: '木',
    parts: [{ char: '利', pinyin: 'lì', meaning: { fr: 'tranchant / profit (donne le son "li")', en: 'sharp / profit (gives the sound "li")' }, tag: 'son' }, { char: '木', pinyin: 'mù', meaning: { fr: 'arbre', en: 'tree' }, tag: 'sens' }],
    logic: { fr: '利(son) au-dessus de 木(arbre) → poire.', en: '利(sound) above 木(tree) → pear.' } },
  { id: 'fr-cheng', hanzi: '橙子', pinyin: 'chéngzi', gloss: { fr: 'orange', en: 'orange' }, cat: 'fruits', rad: '木',
    parts: [{ char: '登', pinyin: 'dēng', meaning: { fr: 'monter (donne le son "cheng")', en: 'to climb (gives the sound "cheng")' }, tag: 'son' }, { char: '木', pinyin: 'mù', meaning: { fr: 'arbre', en: 'tree' }, tag: 'sens' }],
    logic: { fr: '木(arbre) + 登(son) → orange.', en: '木(tree) + 登(sound) → orange.' } },
  { id: 'fr-shizi', hanzi: '柿子', pinyin: 'shìzi', gloss: { fr: 'kaki', en: 'persimmon' }, cat: 'fruits', rad: '木',
    parts: [{ char: '市', pinyin: 'shì', meaning: { fr: 'marché (donne le son "shi")', en: 'market (gives the sound "shi")' }, tag: 'son' }, { char: '木', pinyin: 'mù', meaning: { fr: 'arbre', en: 'tree' }, tag: 'sens' }],
    logic: { fr: '木(arbre) + 市(son) → kaki.', en: '木(tree) + 市(sound) → persimmon.' } },
  { id: 'fr-putao', hanzi: '葡萄', pinyin: 'pútáo', gloss: { fr: 'raisin', en: 'grape' }, cat: 'fruits', rad: '艹',
    parts: [{ char: '葡', pinyin: 'pú', meaning: { fr: '艹(plante) + 匍(son)', en: '艹(plant) + 匍(sound)' }, tag: 'mot' }, { char: '萄', pinyin: 'táo', meaning: { fr: '艹(plante) + 甸(son)', en: '艹(plant) + 甸(sound)' }, tag: 'mot' }],
    logic: { fr: 'Les deux caractères ne veulent rien dire séparément : mot emprunté phonétiquement (comme "kiwi" en français).', en: 'Neither character means anything on its own: a phonetic loanword (like "kiwi" in English).' },
    note: { fr: 'Vient probablement d\'un ancien mot d\'Asie centrale — comme 咖啡 (café) plus loin.', en: 'Likely comes from an old Central Asian word — like 咖啡 (coffee) further down.' } },
  { id: 'fr-boluo', hanzi: '菠萝', pinyin: 'bōluó', gloss: { fr: 'ananas', en: 'pineapple' }, cat: 'fruits', rad: '艹',
    parts: [{ char: '菠', pinyin: 'bō', meaning: { fr: '艹(plante) + 波(son, "vague")', en: '艹(plant) + 波(sound, "wave")' }, tag: 'mot' }, { char: '萝', pinyin: 'luó', meaning: { fr: '艹(plante) + 罗(son)', en: '艹(plant) + 罗(sound)' }, tag: 'mot' }],
    logic: { fr: 'Deux 艹 côte à côte → sans surprise, c\'est une plante.', en: 'Two 艹 side by side → no surprise, it\'s a plant.' } },
  { id: 'fr-xigua', hanzi: '西瓜', pinyin: 'xīguā', gloss: { fr: 'pastèque', en: 'watermelon' }, cat: 'fruits',
    parts: [{ char: '西', pinyin: 'xī', meaning: { fr: 'ouest', en: 'west' }, tag: 'mot' }, { char: '瓜', pinyin: 'guā', meaning: { fr: 'melon — pictogramme d\'un fruit sur une liane', en: 'melon — pictogram of a fruit on a vine' }, tag: 'sens' }],
    logic: { fr: '"melon de l\'ouest" → importée depuis l\'ouest de la Chine il y a des siècles.', en: '"western melon" → imported from western China centuries ago.' } },
  { id: 'fr-caomei', hanzi: '草莓', pinyin: 'cǎoméi', gloss: { fr: 'fraise', en: 'strawberry' }, cat: 'fruits', rad: '艹',
    parts: [{ char: '草', pinyin: 'cǎo', meaning: { fr: 'herbe', en: 'grass' }, tag: 'mot' }, { char: '莓', pinyin: 'méi', meaning: { fr: 'baie (contient 艹)', en: 'berry (contains 艹)' }, tag: 'mot' }],
    logic: { fr: 'herbe + baie → "baie d\'herbe" = fraise.', en: 'grass + berry → "grass berry" = strawberry.' } },

  // ---------------- LÉGUMES ----------------
  { id: 'l-xihongshi', hanzi: '西红柿', pinyin: 'xīhóngshì', gloss: { fr: 'tomate', en: 'tomato' }, cat: 'legumes',
    parts: [{ char: '西', pinyin: 'xī', meaning: { fr: 'ouest', en: 'west' }, tag: 'mot' }, { char: '红', pinyin: 'hóng', meaning: { fr: 'rouge', en: 'red' }, tag: 'mot' }, { char: '柿', pinyin: 'shì', meaning: { fr: 'kaki (木 + 市)', en: 'persimmon (木 + 市)' }, tag: 'mot' }],
    logic: { fr: 'ouest + rouge + kaki → "kaki rouge de l\'ouest" = tomate.', en: 'west + red + persimmon → "western red persimmon" = tomato.' },
    note: { fr: 'Le classique pour expliquer la logique des mots composés chinois.', en: 'The classic example for explaining how Chinese compound words work.' } },
  { id: 'l-tudou', hanzi: '土豆', pinyin: 'tǔdòu', gloss: { fr: 'pomme de terre', en: 'potato' }, cat: 'legumes', rad: '土',
    parts: [{ char: '土', pinyin: 'tǔ', meaning: { fr: 'terre', en: 'earth' }, tag: 'mot' }, { char: '豆', pinyin: 'dòu', meaning: { fr: 'haricot / pois', en: 'bean / pea' }, tag: 'mot' }],
    logic: { fr: 'terre + haricot → "haricot de terre" = pomme de terre.', en: 'earth + bean → "earth bean" = potato.' } },
  { id: 'l-huangguo', hanzi: '黄瓜', pinyin: 'huángguā', gloss: { fr: 'concombre', en: 'cucumber' }, cat: 'legumes',
    parts: [{ char: '黄', pinyin: 'huáng', meaning: { fr: 'jaune', en: 'yellow' }, tag: 'mot' }, { char: '瓜', pinyin: 'guā', meaning: { fr: 'melon', en: 'melon' }, tag: 'mot' }],
    logic: { fr: 'jaune + melon → "melon jaune" = concombre.', en: 'yellow + melon → "yellow melon" = cucumber.' } },
  { id: 'l-baicai', hanzi: '白菜', pinyin: 'báicài', gloss: { fr: 'chou chinois', en: 'Chinese cabbage' }, cat: 'legumes', rad: '艹',
    parts: [{ char: '白', pinyin: 'bái', meaning: { fr: 'blanc', en: 'white' }, tag: 'mot' }, { char: '菜', pinyin: 'cài', meaning: { fr: 'légume (contient 艹)', en: 'vegetable (contains 艹)' }, tag: 'mot' }],
    logic: { fr: 'blanc + légume → "légume blanc" = chou chinois.', en: 'white + vegetable → "white vegetable" = Chinese cabbage.' } },
  { id: 'l-yangcong', hanzi: '洋葱', pinyin: 'yángcōng', gloss: { fr: 'oignon', en: 'onion' }, cat: 'legumes', rad: '艹',
    parts: [{ char: '洋', pinyin: 'yáng', meaning: { fr: 'océan / étranger (contient 氵eau)', en: 'ocean / foreign (contains 氵water)' }, tag: 'mot' }, { char: '葱', pinyin: 'cōng', meaning: { fr: 'ciboule (contient 艹)', en: 'scallion (contains 艹)' }, tag: 'mot' }],
    logic: { fr: '"ciboule étrangère" → oignon, importé de l\'étranger.', en: '"foreign scallion" → onion, imported from abroad.' } },
  { id: 'l-huluobo', hanzi: '胡萝卜', pinyin: 'húluóbo', gloss: { fr: 'carotte', en: 'carrot' }, cat: 'legumes', rad: '艹',
    parts: [{ char: '胡', pinyin: 'hú', meaning: { fr: 'préfixe "importé d\'Asie centrale"', en: 'prefix meaning "imported from Central Asia"' }, tag: 'mot' }, { char: '萝卜', pinyin: 'luóbo', meaning: { fr: 'navet', en: 'turnip' }, tag: 'mot' }],
    logic: { fr: '"navet étranger" → carotte (le vrai navet, 萝卜, est local).', en: '"foreign turnip" → carrot (the real turnip, 萝卜, is local).' } },
  { id: 'l-mogu', hanzi: '蘑菇', pinyin: 'mógu', gloss: { fr: 'champignon', en: 'mushroom' }, cat: 'legumes', rad: '艹',
    parts: [{ char: '蘑', pinyin: 'mó', meaning: { fr: '艹(plante) + 磨(son)', en: '艹(plant) + 磨(sound)' }, tag: 'mot' }, { char: '菇', pinyin: 'gū', meaning: { fr: '艹(plante) + 姑(son)', en: '艹(plant) + 姑(sound)' }, tag: 'mot' }],
    logic: { fr: 'Deux 艹 → encore une plante (même si un champignon n\'est pas vraiment une plante !).', en: 'Two 艹 → yet another plant (even though a mushroom isn\'t really a plant!).' } },
  { id: 'l-lajiao', hanzi: '辣椒', pinyin: 'làjiāo', gloss: { fr: 'piment', en: 'chili pepper' }, cat: 'legumes',
    parts: [{ char: '辣', pinyin: 'là', meaning: { fr: 'épicé / piquant', en: 'spicy / hot' }, tag: 'mot' }, { char: '椒', pinyin: 'jiāo', meaning: { fr: 'épice à baies (contient 木)', en: 'berry spice (contains 木)' }, tag: 'mot' }],
    logic: { fr: 'piquant + épice → piment.', en: 'hot + spice → chili pepper.' } },

  // ---------------- NOURRITURE ----------------
  { id: 'n-mifan', hanzi: '米饭', pinyin: 'mǐfàn', gloss: { fr: 'riz cuit', en: 'cooked rice' }, cat: 'nourriture', rad: '米',
    parts: [{ char: '米', pinyin: 'mǐ', meaning: { fr: 'riz / grain', en: 'rice / grain' }, tag: 'mot' }, { char: '饭', pinyin: 'fàn', meaning: { fr: 'repas (contient 饣 nourriture)', en: 'meal (contains 饣 food)' }, tag: 'mot' }],
    logic: { fr: 'grain + repas → riz cuit, aussi le mot générique pour "repas".', en: 'grain + meal → cooked rice, also the generic word for "meal".' } },
  { id: 'n-miantiao', hanzi: '面条', pinyin: 'miàntiáo', gloss: { fr: 'nouilles', en: 'noodles' }, cat: 'nourriture',
    parts: [{ char: '面', pinyin: 'miàn', meaning: { fr: 'farine / visage', en: 'flour / face' }, tag: 'mot' }, { char: '条', pinyin: 'tiáo', meaning: { fr: 'bande / lanière', en: 'strip / strand' }, tag: 'mot' }],
    logic: { fr: 'farine + bande → nouilles.', en: 'flour + strip → noodles.' } },
  { id: 'n-jiaozi', hanzi: '饺子', pinyin: 'jiǎozi', gloss: { fr: 'raviolis', en: 'dumplings' }, cat: 'nourriture', rad: '饣',
    parts: [{ char: '饣', pinyin: 'shí', meaning: { fr: 'nourriture', en: 'food' }, tag: 'sens' }, { char: '交', pinyin: 'jiāo', meaning: { fr: 'croiser (donne le son "jiao")', en: 'to cross (gives the sound "jiao")' }, tag: 'son' }, { char: '子', pinyin: 'zi', meaning: { fr: 'suffixe', en: 'suffix' }, tag: 'mot' }],
    logic: { fr: '饣(nourriture) + 交(son) → raviolis.', en: '饣(food) + 交(sound) → dumplings.' } },
  { id: 'n-baozi', hanzi: '包子', pinyin: 'bāozi', gloss: { fr: 'bun vapeur', en: 'steamed bun' }, cat: 'nourriture',
    parts: [{ char: '包', pinyin: 'bāo', meaning: { fr: 'envelopper — pictogramme d\'un paquet', en: 'to wrap — pictogram of a package' }, tag: 'sens' }, { char: '子', pinyin: 'zi', meaning: { fr: 'suffixe', en: 'suffix' }, tag: 'mot' }],
    logic: { fr: '"chose enveloppée" → bun fourré cuit à la vapeur.', en: '"wrapped thing" → filled bun cooked in a steamer.' } },
  { id: 'n-cha', hanzi: '茶', pinyin: 'chá', gloss: { fr: 'thé', en: 'tea' }, cat: 'nourriture', rad: '艹',
    parts: [{ char: '艹', pinyin: 'cǎo', meaning: { fr: 'plante', en: 'plant' }, tag: 'sens' }, { char: '人', pinyin: 'rén', meaning: { fr: 'personne (au milieu)', en: 'person (in the middle)' }, tag: 'forme' }, { char: '木', pinyin: 'mù', meaning: { fr: 'arbre (en bas)', en: 'tree (at the bottom)' }, tag: 'sens' }],
    logic: { fr: 'une plante entre les mains d\'une personne, au-dessus d\'un arbre → le thé.', en: 'a plant in a person\'s hands, above a tree → tea.' } },
  { id: 'n-kafei', hanzi: '咖啡', pinyin: 'kāfēi', gloss: { fr: 'café', en: 'coffee' }, cat: 'nourriture', rad: '口',
    parts: [{ char: '咖', pinyin: 'kā', meaning: { fr: '口(bouche, sens="on boit") + 加(son)', en: '口(mouth, meaning "you drink it") + 加(sound)' }, tag: 'mot' }, { char: '啡', pinyin: 'fēi', meaning: { fr: '口(bouche) + 非(son)', en: '口(mouth) + 非(sound)' }, tag: 'mot' }],
    logic: { fr: 'Mot emprunté phonétiquement à "coffee" : les deux 口 signalent juste "ça se boit/dit", le son porte le sens.', en: 'A phonetic loanword from "coffee": the two 口 just signal "this is drunk/said", the sound carries the meaning.' } },
  { id: 'n-niunai', hanzi: '牛奶', pinyin: 'niúnǎi', gloss: { fr: 'lait', en: 'milk' }, cat: 'nourriture',
    parts: [{ char: '牛', pinyin: 'niú', meaning: { fr: 'bœuf / vache', en: 'ox / cow' }, tag: 'mot' }, { char: '奶', pinyin: 'nǎi', meaning: { fr: 'lait (contient 女 femme : à l\'origine "sein nourricier")', en: 'milk (contains 女 woman: originally "nursing breast")' }, tag: 'mot' }],
    logic: { fr: 'vache + lait(maternel) → lait de vache.', en: 'cow + (mother\'s) milk → cow\'s milk.' } },
  { id: 'n-jidan', hanzi: '鸡蛋', pinyin: 'jīdàn', gloss: { fr: 'œuf', en: 'egg' }, cat: 'nourriture', rad: '鸟',
    parts: [{ char: '鸡', pinyin: 'jī', meaning: { fr: 'poulet', en: 'chicken' }, tag: 'mot' }, { char: '蛋', pinyin: 'dàn', meaning: { fr: 'œuf', en: 'egg' }, tag: 'mot' }],
    logic: { fr: 'poulet + œuf → œuf de poule.', en: 'chicken + egg → chicken egg.' } },

  // ---------------- PHRASES (par domaine) ----------------
  // Café
  { id: 'p-cafe1', hanzi: '你好，我要一杯咖啡。', pinyin: 'Nǐ hǎo, wǒ yào yì bēi kāfēi.', gloss: { fr: 'Bonjour, je voudrais un café.', en: 'Hello, I\'d like a coffee.' }, cat: 'phrases', domain: { fr: 'Café', en: 'Coffee Shop' },
    parts: [{ char: '要', pinyin: 'yào', meaning: { fr: 'vouloir (verbe modal, direct devant le verbe/nom)', en: 'to want (modal verb, goes directly before the verb/noun)' }, tag: 'mot' }, { char: '一杯', pinyin: 'yì bēi', meaning: { fr: '一(un) + 杯(classificateur "tasse/verre")', en: '一(one) + 杯(classifier for "cup/glass")' }, tag: 'mot' }, { char: '咖啡', pinyin: 'kāfēi', meaning: { fr: 'café (mot emprunté phonétiquement)', en: 'coffee (phonetic loanword)' }, tag: 'mot' }],
    logic: { fr: 'Entre un nombre et un nom, il faut presque toujours un classificateur : 杯 pour ce qui se boit dans un verre/une tasse.', en: 'Between a number and a noun, you almost always need a classifier: 杯 for things served in a cup/glass.' } },
  { id: 'p-cafe2', hanzi: '可以加糖吗？', pinyin: 'Kěyǐ jiā táng ma?', gloss: { fr: 'Je peux ajouter du sucre ?', en: 'Can I add sugar?' }, cat: 'phrases', domain: { fr: 'Café', en: 'Coffee Shop' },
    parts: [{ char: '可以', pinyin: 'kěyǐ', meaning: { fr: 'pouvoir / avoir la permission (verbe modal)', en: 'to be able to / have permission (modal verb)' }, tag: 'mot' }, { char: '加', pinyin: 'jiā', meaning: { fr: 'ajouter', en: 'to add' }, tag: 'mot' }, { char: '吗', pinyin: 'ma', meaning: { fr: 'particule finale = transforme en question oui/non', en: 'final particle = turns a sentence into a yes/no question' }, tag: 'mot' }],
    logic: { fr: '可以 se met directement devant le verbe, pas besoin de "to" comme en français/anglais.', en: '可以 goes directly before the verb, no "to" needed like in English.' } },
  { id: 'p-cafe3', hanzi: '不要冰，谢谢。', pinyin: 'Bú yào bīng, xièxie.', gloss: { fr: 'Pas de glace, merci.', en: 'No ice, thanks.' }, cat: 'phrases', domain: { fr: 'Café', en: 'Coffee Shop' },
    parts: [{ char: '不要', pinyin: 'bú yào', meaning: { fr: '不(négation) + 要(vouloir)', en: '不(negation) + 要(to want)' }, tag: 'mot' }, { char: '冰', pinyin: 'bīng', meaning: { fr: 'glace', en: 'ice' }, tag: 'mot' }],
    logic: { fr: '不 négative directement le verbe modal 要.', en: '不 directly negates the modal verb 要.' } },
  { id: 'p-cafe4', hanzi: '我要一个可颂和一杯拿铁。', pinyin: 'Wǒ yào yí gè kěsòng hé yì bēi nátiě.', gloss: { fr: 'Je voudrais un croissant et un latte.', en: 'I\'d like a croissant and a latte.' }, cat: 'phrases', domain: { fr: 'Café', en: 'Coffee Shop' },
    parts: [{ char: '一个可颂', pinyin: 'yí gè kěsòng', meaning: { fr: 'un(classificateur générique 个) croissant', en: 'one (generic classifier 个) croissant' }, tag: 'mot' }, { char: '和', pinyin: 'hé', meaning: { fr: '"et" — relie deux groupes nominaux', en: '"and" — links two noun phrases' }, tag: 'mot' }, { char: '一杯拿铁', pinyin: 'yì bēi nátiě', meaning: { fr: 'un(classificateur 杯) latte', en: 'one (classifier 杯) latte' }, tag: 'mot' }],
    logic: { fr: '和 relie ici deux groupes NOM+classificateur (même nature) → correct. Voir Grammaire pour la règle complète.', en: '和 here links two NOUN+classifier groups (same kind) → correct. See Grammar for the full rule.' } },
  { id: 'p-cafe5', hanzi: '谢谢，多少钱？', pinyin: 'Xièxie, duōshao qián?', gloss: { fr: 'Merci, combien ça coûte ?', en: 'Thanks, how much is it?' }, cat: 'phrases', domain: { fr: 'Café', en: 'Coffee Shop' },
    parts: [{ char: '多少', pinyin: 'duōshao', meaning: { fr: 'combien (pour quantité ≥ à priori élevée)', en: 'how much/many (for a quantity assumed to be larger)' }, tag: 'mot' }, { char: '钱', pinyin: 'qián', meaning: { fr: 'argent', en: 'money' }, tag: 'mot' }],
    logic: { fr: 'Littéralement "combien d\'argent ?".', en: 'Literally "how much money?".' } },

  // Bavardage / gossip
  { id: 'p-gos1', hanzi: '你知道吗？', pinyin: 'Nǐ zhīdào ma?', gloss: { fr: 'Tu sais quoi ?', en: 'You know what?' }, cat: 'phrases', domain: { fr: 'Bavardage', en: 'Gossip' },
    parts: [{ char: '知道', pinyin: 'zhīdào', meaning: { fr: 'savoir', en: 'to know' }, tag: 'mot' }, { char: '吗', pinyin: 'ma', meaning: { fr: 'particule question oui/non', en: 'yes/no question particle' }, tag: 'mot' }],
    logic: { fr: 'L\'accroche classique avant un ragot.', en: 'The classic opener before some gossip.' } },
  { id: 'p-gos2', hanzi: '听说她换工作了。', pinyin: 'Tīngshuō tā huàn gōngzuò le.', gloss: { fr: 'Il paraît qu\'elle a changé de travail.', en: 'I heard she changed jobs.' }, cat: 'phrases', domain: { fr: 'Bavardage', en: 'Gossip' },
    parts: [{ char: '听说', pinyin: 'tīngshuō', meaning: { fr: 'littéralement "entendre dire" = il paraît que / on dit que', en: 'literally "hear said" = I heard that / people say that' }, tag: 'mot' }, { char: '换工作', pinyin: 'huàn gōngzuò', meaning: { fr: 'changer de travail', en: 'to change jobs' }, tag: 'mot' }, { char: '了', pinyin: 'le', meaning: { fr: 'particule d\'action accomplie (pas "avoir" !)', en: 'completed-action particle (not "have"!)' }, tag: 'mot' }],
    logic: { fr: '了 en fin de phrase signale que l\'action a eu lieu / un changement d\'état — ce n\'est pas un auxiliaire comme "avoir".', en: '了 at the end of a sentence signals that the action happened / a change of state — it is not an auxiliary like "have".' },
    note: { fr: '听说 est LE mot-clé pour rapporter un ragot en chinois.', en: '听说 is THE key word for relaying gossip in Chinese.' } },
  { id: 'p-gos3', hanzi: '真的假的？', pinyin: 'Zhēn de jiǎ de?', gloss: { fr: 'Sérieux ?? (vrai ou faux ?)', en: 'Seriously?? (true or false?)' }, cat: 'phrases', domain: { fr: 'Bavardage', en: 'Gossip' },
    parts: [{ char: '真的', pinyin: 'zhēn de', meaning: { fr: 'vrai', en: 'true' }, tag: 'mot' }, { char: '假的', pinyin: 'jiǎ de', meaning: { fr: 'faux', en: 'false' }, tag: 'mot' }],
    logic: { fr: 'Question "vrai (ou) faux ?" juxtaposée, très courant à l\'oral.', en: 'A juxtaposed "true (or) false?" question, very common in spoken Chinese.' } },
  { id: 'p-gos4', hanzi: '别告诉别人。', pinyin: 'Bié gàosu biérén.', gloss: { fr: 'Ne le dis à personne.', en: 'Don\'t tell anyone.' }, cat: 'phrases', domain: { fr: 'Bavardage', en: 'Gossip' },
    parts: [{ char: '别', pinyin: 'bié', meaning: { fr: 'ne... pas (impératif négatif)', en: 'don\'t (negative imperative)' }, tag: 'mot' }, { char: '告诉', pinyin: 'gàosu', meaning: { fr: 'dire / informer', en: 'to tell / inform' }, tag: 'mot' }, { char: '别人', pinyin: 'biérén', meaning: { fr: 'les autres / autrui', en: 'other people / others' }, tag: 'mot' }],
    logic: { fr: '别 + verbe = ordre négatif ("ne fais pas...").', en: '别 + verb = negative command ("don\'t do...").' } },
  { id: 'p-gos5', hanzi: '我也这么觉得。', pinyin: 'Wǒ yě zhème juéde.', gloss: { fr: 'Je pense pareil.', en: 'I think the same.' }, cat: 'phrases', domain: { fr: 'Bavardage', en: 'Gossip' },
    parts: [{ char: '也', pinyin: 'yě', meaning: { fr: 'aussi (se place avant le verbe, pas après comme en français)', en: 'also (goes before the verb, not after like in English)' }, tag: 'mot' }, { char: '这么', pinyin: 'zhème', meaning: { fr: 'comme ça / ainsi', en: 'like this / so' }, tag: 'mot' }, { char: '觉得', pinyin: 'juéde', meaning: { fr: 'penser / trouver que', en: 'to think / feel that' }, tag: 'mot' }],
    logic: { fr: '也 se place toujours juste avant le verbe.', en: '也 always goes right before the verb.' } },

  // Transport
  { id: 'p-trans1', hanzi: '地铁站在哪儿？', pinyin: 'Dìtiě zhàn zài nǎr?', gloss: { fr: 'Où est la station de métro ?', en: 'Where\'s the subway station?' }, cat: 'phrases', domain: { fr: 'Transport', en: 'Transport' },
    parts: [{ char: '地铁站', pinyin: 'dìtiě zhàn', meaning: { fr: 'station de métro', en: 'subway station' }, tag: 'mot' }, { char: '在', pinyin: 'zài', meaning: { fr: 'se trouver / être à', en: 'to be located / to be at' }, tag: 'mot' }, { char: '哪儿', pinyin: 'nǎr', meaning: { fr: 'où', en: 'where' }, tag: 'mot' }],
    logic: { fr: 'Structure fixe : [lieu] + 在 + 哪儿 pour demander un emplacement.', en: 'Fixed structure: [place] + 在 + 哪儿 to ask where something is.' } },
  { id: 'p-trans2', hanzi: '这张票多少钱？', pinyin: 'Zhè zhāng piào duōshao qián?', gloss: { fr: 'Ce billet coûte combien ?', en: 'How much is this ticket?' }, cat: 'phrases', domain: { fr: 'Transport', en: 'Transport' },
    parts: [{ char: '这张票', pinyin: 'zhè zhāng piào', meaning: { fr: '这(ce) + 张(classificateur objets plats) + 票(billet)', en: '这(this) + 张(classifier for flat objects) + 票(ticket)' }, tag: 'mot' }],
    logic: { fr: '张 classifie les objets plats et fins : billets, papiers, tickets.', en: '张 classifies flat, thin objects: tickets, paper, cards.' } },
  { id: 'p-trans3', hanzi: '下一站是什么？', pinyin: 'Xià yí zhàn shì shénme?', gloss: { fr: 'Quelle est la prochaine station ?', en: 'What\'s the next station?' }, cat: 'phrases', domain: { fr: 'Transport', en: 'Transport' },
    parts: [{ char: '下一站', pinyin: 'xià yí zhàn', meaning: { fr: '下(suivant) + 一(un) + 站(station/arrêt)', en: '下(next) + 一(one) + 站(station/stop)' }, tag: 'mot' }, { char: '是', pinyin: 'shì', meaning: { fr: 'être', en: 'to be' }, tag: 'mot' }],
    logic: { fr: '下一 = "le suivant", très utile aussi pour "下一个" (le prochain, en général).', en: '下一 = "the next one", also handy in "下一个" (the next one, in general).' } },
  { id: 'p-trans4', hanzi: '我要打车。', pinyin: 'Wǒ yào dǎchē.', gloss: { fr: 'Je veux prendre un taxi.', en: 'I want to take a taxi.' }, cat: 'phrases', domain: { fr: 'Transport', en: 'Transport' },
    parts: [{ char: '要', pinyin: 'yào', meaning: { fr: 'vouloir (modal)', en: 'to want (modal)' }, tag: 'mot' }, { char: '打车', pinyin: 'dǎchē', meaning: { fr: 'littéralement "frapper une voiture" = héler un taxi', en: 'literally "to hit a car" = to hail a taxi' }, tag: 'mot' }],
    logic: { fr: '打 apparaît dans plein d\'expressions figées (打电话 téléphoner, 打球 jouer au ballon...) sans lien direct avec "frapper".', en: '打 shows up in tons of fixed expressions (打电话 to phone, 打球 to play ball...) with no direct link to "hitting".' } },

  // Politesse / base
  { id: 'p-pol1', hanzi: '很高兴认识你。', pinyin: 'Hěn gāoxìng rènshi nǐ.', gloss: { fr: 'Ravi de te rencontrer.', en: 'Nice to meet you.' }, cat: 'phrases', domain: { fr: 'Politesse', en: 'Politeness' },
    parts: [{ char: '很高兴', pinyin: 'hěn gāoxìng', meaning: { fr: 'très content (很 ne veut presque rien dire ici, obligatoire devant un adjectif seul)', en: 'very happy (很 barely means anything here, it\'s just required before a standalone adjective)' }, tag: 'mot' }, { char: '认识', pinyin: 'rènshi', meaning: { fr: 'connaître / faire la connaissance de', en: 'to know / to get acquainted with' }, tag: 'mot' }],
    logic: { fr: '很 devant un adjectif seul n\'est souvent qu\'une béquille grammaticale, pas un vrai "très".', en: '很 before a lone adjective is often just a grammatical crutch, not a real "very".' } },
  { id: 'p-pol2', hanzi: '对不起，我迟到了。', pinyin: 'Duìbuqǐ, wǒ chídào le.', gloss: { fr: 'Désolé, je suis en retard.', en: 'Sorry, I\'m late.' }, cat: 'phrases', domain: { fr: 'Politesse', en: 'Politeness' },
    parts: [{ char: '对不起', pinyin: 'duìbuqǐ', meaning: { fr: 'désolé (litt. "je ne peux pas te faire face")', en: 'sorry (litt. "I cannot face you")' }, tag: 'mot' }, { char: '迟到', pinyin: 'chídào', meaning: { fr: 'arriver en retard', en: 'to arrive late' }, tag: 'mot' }, { char: '了', pinyin: 'le', meaning: { fr: 'accompli / état atteint', en: 'completed / state reached' }, tag: 'mot' }],
    logic: { fr: '了 confirme que le retard est déjà un fait accompli.', en: '了 confirms that the lateness is already a done deal.' } },
  { id: 'p-pol3', hanzi: '没关系。', pinyin: 'Méi guānxi.', gloss: { fr: 'Ce n\'est pas grave.', en: 'It\'s no big deal.' }, cat: 'phrases', domain: { fr: 'Politesse', en: 'Politeness' },
    parts: [{ char: '没', pinyin: 'méi', meaning: { fr: 'négation (utilisée avec 有 et certains états)', en: 'negation (used with 有 and certain states)' }, tag: 'mot' }, { char: '关系', pinyin: 'guānxi', meaning: { fr: 'relation / importance', en: 'relation / importance' }, tag: 'mot' }],
    logic: { fr: 'Littéralement "pas de relation/importance" → "aucun problème".', en: 'Literally "no relation/importance" → "no problem".' } },
  { id: 'p-pol4', hanzi: '可以帮我一下吗？', pinyin: 'Kěyǐ bāng wǒ yíxià ma?', gloss: { fr: 'Tu peux m\'aider un instant ?', en: 'Can you help me for a moment?' }, cat: 'phrases', domain: { fr: 'Politesse', en: 'Politeness' },
    parts: [{ char: '可以', pinyin: 'kěyǐ', meaning: { fr: 'pouvoir (modal)', en: 'to be able to (modal)' }, tag: 'mot' }, { char: '帮我', pinyin: 'bāng wǒ', meaning: { fr: 'aider moi (pas de préposition "à")', en: 'to help me (no preposition needed)' }, tag: 'mot' }, { char: '一下', pinyin: 'yíxià', meaning: { fr: 'un petit coup / un instant (adoucit la demande)', en: 'a little bit / a moment (softens the request)' }, tag: 'mot' }],
    logic: { fr: '一下 après un verbe rend la demande plus légère, moins directe.', en: '一下 after a verb makes the request lighter, less direct.' } },
];

// ---------------- GRAMMAIRE : pièges & règles utiles ----------------
const GRAMMAR = [
  {
    id: 'g-he',
    title: { fr: '和 / 跟 ne relient que des mots de MÊME NATURE', en: '和 / 跟 only link words of the SAME KIND' },
    rule: { fr: '和 (hé) et 跟 (gēn) veulent dire "et", mais seulement entre deux mots de même type : deux noms, deux pronoms, deux groupes nominaux. On ne les utilise JAMAIS pour relier deux verbes ou deux phrases.', en: '和 (hé) and 跟 (gēn) both mean "and", but only between two words of the same type: two nouns, two pronouns, two noun phrases. They are NEVER used to link two verbs or two clauses.' },
    examples: [
      { hanzi: '我和你', pinyin: 'wǒ hé nǐ', fr: { fr: 'toi et moi', en: 'you and me' }, ok: true, note: { fr: 'pronom + pronom', en: 'pronoun + pronoun' } },
      { hanzi: '咖啡和茶', pinyin: 'kāfēi hé chá', fr: { fr: 'café et thé', en: 'coffee and tea' }, ok: true, note: { fr: 'nom + nom', en: 'noun + noun' } },
      { hanzi: '我吃和喝', pinyin: 'wǒ chī hé hē', fr: { fr: '(incorrect) "je mange et bois"', en: '(incorrect) "I eat and drink"' }, ok: false, note: { fr: '和 ne relie pas deux verbes', en: '和 does not link two verbs' } },
      { hanzi: '我吃饭，然后喝茶', pinyin: 'wǒ chīfàn, ránhòu hē chá', fr: { fr: 'je mange, puis je bois du thé', en: 'I eat, then I drink tea' }, ok: true, note: { fr: 'pour enchaîner des actions → 然后 (ensuite), pas 和', en: 'to chain actions → use 然后 (then), not 和' } },
    ],
  },
  {
    id: 'g-le',
    title: { fr: '了 marque un accompli, ce n\'est pas "avoir"', en: '了 marks a completed action, it is not "have"' },
    rule: { fr: '了 (le) placé après le verbe (ou en fin de phrase) signale qu\'une action est terminée ou qu\'un changement d\'état a eu lieu. Le verbe chinois ne se conjugue jamais — 了 n\'est pas un auxiliaire comme "avoir" en français, c\'est une particule d\'aspect.', en: '了 (le), placed after the verb (or at the end of the sentence), signals that an action is finished or that a change of state has occurred. Chinese verbs never conjugate — 了 is not an auxiliary like "have" in English, it\'s an aspect particle.' },
    examples: [
      { hanzi: '我吃了', pinyin: 'wǒ chī le', fr: { fr: 'j\'ai mangé', en: 'I ate' }, ok: true },
      { hanzi: '他走了', pinyin: 'tā zǒu le', fr: { fr: 'il est parti', en: 'he left' }, ok: true },
      { hanzi: '我吃', pinyin: 'wǒ chī', fr: { fr: 'je mange (pas encore fini / habituel)', en: 'I eat (not finished yet / habitual)' }, ok: true, note: { fr: 'sans 了, l\'action n\'est pas marquée comme terminée', en: 'without 了, the action is not marked as completed' } },
    ],
  },
  {
    id: 'g-modaux',
    title: { fr: '可以 / 要 / 想 — les verbes modaux', en: '可以 / 要 / 想 — modal verbs' },
    rule: { fr: 'Un verbe modal se place directement devant le verbe principal, sans rien entre les deux (pas de "de" ni de "to"). 可以 (kěyǐ) = pouvoir/permission, 要 (yào) = vouloir/devoir, 想 (xiǎng) = avoir envie de.', en: 'A modal verb goes directly before the main verb, with nothing in between (no "to"). 可以 (kěyǐ) = can/may, 要 (yào) = want to/must, 想 (xiǎng) = would like to.' },
    examples: [
      { hanzi: '我要喝水', pinyin: 'wǒ yào hē shuǐ', fr: { fr: 'je veux boire de l\'eau', en: 'I want to drink water' }, ok: true },
      { hanzi: '我可以走吗？', pinyin: 'wǒ kěyǐ zǒu ma?', fr: { fr: 'je peux partir ?', en: 'can I leave?' }, ok: true },
      { hanzi: '我想你', pinyin: 'wǒ xiǎng nǐ', fr: { fr: 'tu me manques (litt. "je pense à toi")', en: 'I miss you (litt. "I think of you")' }, ok: true, note: { fr: '想 + personne = "penser à / manquer"', en: '想 + person = "to think of / to miss"' } },
    ],
  },
  {
    id: 'g-classif',
    title: { fr: '量词 — les classificateurs (obligatoires !)', en: '量词 — classifiers (mandatory!)' },
    rule: { fr: 'Entre un nombre et un nom, il faut presque toujours un classificateur — comme "une TRANCHE de pain" en français, mais quasi systématique en chinois. Chaque catégorie d\'objet a le sien : 个 (gè) générique, 杯 (bēi) pour les boissons servies, 张 (zhāng) pour les objets plats, 只 (zhī) pour les animaux.', en: 'Between a number and a noun, you almost always need a classifier — like a "SLICE of bread" in English, but nearly systematic in Chinese. Every category of object has its own: 个 (gè) generic, 杯 (bēi) for served drinks, 张 (zhāng) for flat objects, 只 (zhī) for animals.' },
    examples: [
      { hanzi: '一个人', pinyin: 'yí gè rén', fr: { fr: 'une personne', en: 'one person' }, ok: true, note: { fr: '个 = générique, à utiliser par défaut', en: '个 = generic, use it by default' } },
      { hanzi: '一杯咖啡', pinyin: 'yì bēi kāfēi', fr: { fr: 'un café', en: 'one coffee' }, ok: true, note: { fr: '杯 = ce qui se sert dans une tasse/un verre', en: '杯 = things served in a cup/glass' } },
      { hanzi: '两张票', pinyin: 'liǎng zhāng piào', fr: { fr: 'deux billets', en: 'two tickets' }, ok: true, note: { fr: '张 = objets plats et fins', en: '张 = flat, thin objects' } },
      { hanzi: '一咖啡', pinyin: 'yì kāfēi', fr: { fr: '(incorrect, classificateur manquant)', en: '(incorrect, missing classifier)' }, ok: false },
    ],
  },
];

const TAG_LABEL = {
  sens: { fr: 'sens', en: 'meaning' },
  son: { fr: 'son', en: 'sound' },
  mot: { fr: 'mot', en: 'word' },
  forme: { fr: 'forme', en: 'shape' },
};

// Emoji indexés par caractère(s) — utilisé pour les cartes, la décomposition
// et les radicaux. Sert d'ancrage visuel + rend la logique des mots composés
// immédiatement lisible (ex: 火🔥 + 鸡🐔 → 火鸡🦃).
const EMOJI = {
  // radicaux / fondations
  '木': '🌳', '艹': '🌿', '氵': '💧', '水': '💧', '火': '🔥', '灬': '🔥',
  '土': '🟫', '金': '🪙', '鸟': '🐦', '隹': '🐦', '犭': '🐾', '鱼': '🐟',
  '虫': '🐛', '豕': '🐖', '饣': '🍽️', '米': '🌾', '口': '👄', '女': '👩',
  '子': '🧒', '人': '🧍', '日': '☀️', '月': '🌙', '山': '⛰️',
  // couleurs / directions qui reviennent dans les mots composés
  '红': '🔴', '黄': '🟡', '白': '⚪', '西': '🧭',
  // animaux
  '鸡': '🐔', '鸭': '🦆', '鹅': '🦢', '鸽': '🕊️', '鹰': '🦅', '鲸': '🐋',
  '鲤鱼': '🐟', '鲨鱼': '🦈', '猫': '🐱', '狗': '🐶', '猴子': '🐒', '狼': '🐺',
  '猪': '🐷', '蚂蚁': '🐜', '蝴蝶': '🦋', '蜜蜂': '🐝', '牛': '🐮', '鹿': '🦌',
  '火鸡': '🦃', '熊猫': '🐼', '熊': '🐻', '猫头鹰': '🦉', '长颈鹿': '🦒',
  '河马': '🦛', '蜗牛': '🐌',
  // fruits
  '苹果': '🍎', '果': '🍏', '桃': '🍑', '梨': '🍐', '橙子': '🍊', '柿子': '🟠',
  '葡萄': '🍇', '菠萝': '🍍', '西瓜': '🍉', '草莓': '🍓', '瓜': '🍈',
  // légumes
  '西红柿': '🍅', '土豆': '🥔', '黄瓜': '🥒', '白菜': '🥬', '洋葱': '🧅',
  '胡萝卜': '🥕', '豆': '🫘', '蘑菇': '🍄', '辣椒': '🌶️',
  // nourriture / boissons
  '米饭': '🍚', '面条': '🍜', '饺子': '🥟', '包子': '🥯', '茶': '🍵',
  '咖啡': '☕', '牛奶': '🥛', '鸡蛋': '🥚',
};
